### ISSUE TITLE
Adding simple numbers not optimized

### ISSUE THREAD

**Issue by FL0RIANMEYER** [facebook/prepack#1006]
In:
```javascript
(function () {    
    var _2 = __abstract('number', 'x');    
    var _1 = _2 + 5;    
    var _0 = 4 + _1;    
    console.log(_0);    
})();    
```

out:
```javascript
(function () {    
  var _5 = x;    
  var _4 = _5 + 5;    
  var _3 = 4 + _4;    
  console.log(_3);    
})();  
```

expected:
```javascript
(function () {    
  var _5 = x;    
  var _3 = 4 + _5 + 5;    
  console.log(_3);    
})();  
```

**Comment by NTillmann** [comment]
Floating point computations are not necessarily associative, so we currently err on the side of correctness and do not attempt to further optimize the result.

You can get rid of the intermediate identifiers by supplying the option --inlineExpressions on the command line. If you are using the web UI, then we have an open issue to add the ability to change options there (#958).
