### ISSUE TITLE
ProxyValue sets $Realm to undefined

### ISSUE THREAD

**Issue by hermanventer** [facebook/prepack#1022]
ProxyValue sets its $Realm property to undefined and possesses its own realm property. This is bizarre and breaks the invariant the every Value has defined $Realm property.

If possible, just use $Realm. If not, document this and do something other than setting $Realm to undefined.

**Comment by gustavderdrache** [comment]
Prepack will crash attempting to evaluate even this reduced case:

```js
new Proxy(function () {}, {});
```

I found this trying to run this on a React code base that wasn't set to production. In dev mode,
 the SyntheticEvent class is [proxied](https://github.com/facebook/react/blob/v16.1.1/packages/events/SyntheticEvent.js#L237).

**Comment by NTillmann** [comment]
Thanks for pointing this out, @gustavderdrache! I created #1235 to track that issue.
