### ISSUE TITLE
Remove __annotate function

### ISSUE THREAD

**Issue by hermanventer** [facebook/prepack#1023]
This is used in an old version of an internal test. Update or remove that test and then remove this function.

**Comment by M-ZubairAhmed** [comment]
Can I take this one ?

**Comment by hermanventer** [comment]
Unless you are Facebook employee, sadly no. There are some changes we need to make to internal test passes.

In general, only look for issues with the help wanted label.

**Comment by NTillmann** [comment]
This is done.
