### ISSUE TITLE
How to split prepack builds

### ISSUE THREAD

**Issue by FL0RIANMEYER** [facebook/prepack#1027]
Is it possible to export the context of a module build for certain varaibales like https://github.com/facebook/prepack/issues/561#issuecomment-299334422 to use as an import for another build?

So it might be possible to shim export to get the context and use a shim import/require to use this extracted context as abstract imput.

So this could eliminate the unknown nested abstraction problem when prepacking node modules.

![This graph becomes disconnected when the right-most node in the gray area on the left is removed](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Network_Community_Structure.svg/220px-Network_Community_Structure.svg.png)

This way i could save the context and build for a mudule (e.g. express).

Every time I use this module, I could check if the context matches my import and underlaying use case and import the pre-packaged module instead of the original heavy module.

**Comment by NTillmann** [comment]
We recently landed a new feature that goes into this direction: #912 - serializing independent functions. @cblappert --- we need some good documentation for this feature, what it does, what problem it solves, and what it doesn't do (yet)...

When you want to prepack a module factory, Prepack needs to know about the environment. One could think of that environment consisting of two parts:
- other modules that can be accessed by calling `require` --- I think that's what you were mainly thinking about. Different ways of dealing with that: If we could separately Prepack that module, we could create a shim from the structure of the produced module value --- however, this would only really be safe if we assume that the module value, and everything reachable from it, is frozen. Alternatively, it should be easy to model the module value that comes back as just an abstract value, of which nothing is known. Alternatively, with a bit more work we could leverage any existing type annotations to inform Prepack about further aspects of the model value, assuming we trust that the static type annotations will be honored at runtime.
- the `global` object, and all built-ins. The feature that was just added to Prepack allows prepacking additional functions that just depend on that, assuming that the global object and all built-ins have not been mutated after the end of global code execution. Again, ideally all of those objects and built-ins would actually get frozen at the end of global code execution to enforce this.

**Comment by NTillmann** [comment]
I hope we answered the question. Feel free to reopen to discuss more.
