### ISSUE TITLE
Print useful call stacks from prepack-cli

### ISSUE THREAD

**Issue by hermanventer** [facebook/prepack#1048]
Currently, if prepack terminates on a FatalError it enters a code path that dumps the fatal error message and the stack that led to the fatal error.

This is not interesting as the fatal error is just a quick way to terminate prepack after the real cause of the error has been report via a CompilerDiagnostic instance to the registered error handler. 

Make the exception handling code aware of FatalError and let them silently kill the process. Instead, when printing out the diagnostics, use the callStack property to get a stack that relates to the code being prepacked, rather than the internal code of Prepack.

**Comment by NTillmann** [comment]
This was addressed by referenced merged pull request.
