### ISSUE TITLE
Please add documentation on README.md for webpack configuration

### ISSUE THREAD

**Issue by odykyi** [facebook/prepack#1077]

**Comment by archiekh** [comment]
Can add example from https://github.com/gajus/prepack-webpack-plugin

**Comment by atav32** [comment]
Or just a link to https://github.com/gajus/prepack-webpack-plugin

**Comment by baptistemanson** [comment]
I think this issue is now resolved!

**Comment by NTillmann** [comment]
Thanks to @artiebits for the merged pull request!
