### ISSUE TITLE
Referentializer generates wrong mutable scope array and access function name

### ISSUE THREAD

**Issue by yinghuitan** [facebook/prepack#1084]
https://github.com/facebook/prepack/blob/master/src/serializer/Referentializer.js#L59-L60
It tries to generate the access function named "__get_scope_binding", while it results in "__scope_0" because of incorrect using of "scopeNameGenerator".

See #1082 for an example of detailed generated code.

**Comment by NTillmann** [comment]
Names are now reasonable.
