### ISSUE TITLE
Make Effects clean to apply and revert

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#1090]
Currently applying `Effects` from an `evaluateForEffects` call will mutate the `ModifiedBindings` and `ModifiedProperties` of the Effects passed in. Add the ability to apply Effects without mutating these portions so that Effects can be stored and properly applied multiple times.

**Comment by hermanventer** [comment]
Some careful thinking is needed here. Applying effects multiple times can be a bug farm. It might be better to check that effects are applied exactly once, treating join as a form of apply.

**Comment by NTillmann** [comment]
Bug triage conclusion: Not gonna happen.
