### ISSUE TITLE
Repeated argument identifiers with inlined expressions. 

### ISSUE THREAD

**Issue by simonhj** [facebook/prepack#1136]
I noticed that PrePack generates duplicate argument names when inlining expressions. Take for instance the test in `test/serializer/basic/CapturedScope.js`. PrePacked with `--inlineExpressions` it generates several functions like
```javascript
var $_1 = function (c, __scope_2, __scope_2) {
    var __captured__scope_2 = __scope_1(__scope_2);

    var __captured__scope_2 = __scope_1(__scope_2);

    __captured__scope_2[1]++;
    __captured__scope_2[2]++;
    return c();
  };
```
Duplicate arguments are a syntax error in strict mode and generally confusing.

**Comment by simonhj** [comment]
Smaller test that exhibit same problem
```javascript
function f (x) {
  var valueA = 0;
  function c() {
    x ? valueA++ : valueA += 2;
    return valueA;
  }

  return c;
}

var s = f(true);
var r = f(false);
```

**Comment by NTillmann** [comment]
Issue addressed by merged pull request.
