### ISSUE TITLE
Check that intrinsic names are unique

### ISSUE THREAD

**Issue by hermanventer** [facebook/prepack#1155]
When creating a model for an intrinsic object via __abstract(template, "name") check that "name" has not already been used in the model.

**Comment by prometheansacrifice** [comment]
Is there a data structure somewhere that maintains a list of all Abstract values? I couldn't find (at the first look) one in [`createFromTemplate`](https://github.com/facebook/prepack/blob/master/src/values/AbstractValue.js#L496)

**Comment by hermanventer** [comment]
There isn't. Sounds like a useful addition.
