### ISSUE TITLE
AbstractObjectValue property accesses may generate unnecessary code

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1179]
```js
// Copies of .bar:2
var foo = __makeSimple(__abstract({}, "foo"));
foo.bar = {a: 1};
this.foo = foo;
```

is a serializer test case that fails because we generate too many (unused!) accesses to `.bar`:

```js
var foo;

(function () {
  foo = foo;
  var _1 = foo;
  var _$0 = _1.bar;
  var _$1 = _1.bar;
  var _$2 = _1.bar;
  _1.bar = {
    a: 1
  };
})();
```

The `_$n` thingies are created via `createTemporalFromBuildFunction` called indirectly from places like `PropertiesImplementation.PutValue`. Still, there seems to be something not quite right, as `_$1` and `_$2` are not used (could they be marked as `isPure` and then get eliminated?).

**Comment by hermanventer** [comment]
It is not clear to me why _$0 is needed.
