### ISSUE TITLE
Issue with getPureBinaryOperationResultType

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#1182]
The following example fails to interpret in Prepack:

```javascript
// add at runtime:var global=this;this.nativePerformanceNow = Date.now;
if (global.__assumeDataProperty) __assumeDataProperty(this, "nativePerformanceNow", function() {
  if (this.__residual)
    return __residual("number", function(global) {
      return global.nativePerformanceNow();
    }, global);
  else return this.nativePerformanceNow();
}, "SKIP_INVARIANT");
let performanceNow = nativePerformanceNow;

let timespans = {};

function addTimespan(key) {
  timespans[key] = {};
}

function startTimespan(key) {
  if (timespans[key]) return;
  timespans[key] = { startTime: performanceNow() };
}

function stopTimespan(key) {
  const timespan = timespans[key];
  if (!timespan || !timespan.startTime) return;
  timespan.endTime = performanceNow();
  // Following line has a problem
  timespan.totalTime = timespan.endTime - (timespan.startTime || 0);
}

startTimespan("hello");
stopTimespan("hello");

inspect = function() { return true; }
```

`timespan.endTime` seems to be a conditional `AbstractValue` that is `undefined | some abstract number` which is not allowed during subtraction.

**Comment by hermanventer** [comment]
I looked into this and there are two issues here:
1) Following if (!timespan || !timespan.startTime) return; the inverse condition is not push to the path.
2) timespan.startTime || 0 does not use the path to evaluate timespan.startTime as a condition.

The second is an easy fix. The first is going to be a bit more work. I've know about it for a while but so far it has not come up. I guess my luck has run out. I was hoping that Simon might perhaps take an interest in this one.
