### ISSUE TITLE
Make it easy to find out which version of prepack is running

### ISSUE THREAD

**Issue by hermanventer** [facebook/prepack#1213]
Add a function "__prepackVersion" that returns the version of the Prepack that is running the code. Also add a command line option for printing out the version string. Make sure this is in sync with the version string in package.json.

Update the prepack.io website to display the version of Prepack that it is running.

This is not blocking anything super important but makes investigations into weird behavior much easier.

**Comment by artiebits** [comment]
Hi, can you assign it to me, please? 
I’ve added the version as a command line option but confusing about `__prepackVersion`. Can you explain me your vision of these feature? I have an idea to implement `prepackVersion` in `prepack-standalone.js` that will be reachable from Prepack object:

```{ 
  prepackVersion: [Getter],
  prepackNodeCLI: [Getter],
  prepackNodeCLISync: [Getter],
  InitializationError: [Getter],
  prepackSources: [Getter],
  prepackString: [Getter],
  prepack: [Getter],
  prepackFromAst: [Getter],
  prepackStdin: [Function: prepackStdin],
  prepackFile: [Function: prepackFile],
  prepackFileSync: [Function: prepackFileSync] 
}
```

to use it like this:
```
var Prepack = require("prepack");
console.log(Prepack.prepackVersion)
```

In that way we also can get and display the version on the website.

But what is your vision?

**Comment by hermanventer** [comment]
__prepackVersion() would allow the code being prepacked to behave differently depending on the version of Prepack. I don't really have a use case for it. Your idea seems just fine and I'd be happy if you went ahead with it.
