### ISSUE TITLE
Circular residual function references aren't serialized properly

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#1222]
When residual functions reference eachother, there is no guarantee that the `.bind` statements will be emitted in the correct order (or that you can define the functions correctly with just `.bind` statements when functions have a cyclic reference a > b > c > a).

Blocks #1093 

Repro -- small variant on `CapturedScope.js`:

```javascript
// serialized function clone count: 0
function f (x) {
  var valueA = 0;
  var valueB = 1;
  var valueC = 2;

  function a() { // no inline
    valueA++;
    return b();
  }

  function b() { // no inline
    valueA++;
    valueB++;
    return c();
  }

  function c() {
    if (valueA % 3) a();
    x ? valueC++ : valueC += 2;
    return valueA * valueB * valueC;
  }

  return a;
}

var s = f(true);
var r = f(false);

inspect = function() {
  return s() + ' ' + r();
}
```

**Comment by NTillmann** [comment]
The "bind" call in question should be generated here: https://github.com/facebook/prepack/blob/master/src/serializer/ResidualFunctions.js#L517

Note that this is a kind-of optional optimization. Issuing the "bind" call is guarded by an `if` statement in front of it, which already lists a bunch of reasons which rule out that "bind" optimizations. As a quick work-around, you could disable the "bind" optimization altogether. But really, the question is how to express the condition.

**Comment by NTillmann** [comment]
It might be enough to just check whether the immediate `residualBinding.serializedValue` itself is a `FunctionValue`, a binding just operates on that immediate value, and initialization of any nested structured are taken care off separately.
