### ISSUE TITLE
Add ability to serialize references to bindings in residual heap

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#1245]
This is blocking #1142.

Currently the serializer cannot serialize a program like this:

```js
(function() {
  var x = 0;
  callThis(function() {
    return x++;
  });
  return x;
})();
```

This is because there is no way to serialize a binding. We can only serialize the value of a binding. E.g. something like this:

```js
(function() {
  var x = 0;
  callThis(function() {
    return x++;
  });
  return 0;
})();
```

However, since we may have mutated the binding by the time we get there, we need to read from it.

There are various incorrect attempts to solve this in #1142. I tried to this by calling [referentialize for a specific binding](https://github.com/facebook/prepack/pull/1142/commits/dbb8a2e1d352e7cd510355b48a8868d6d12d95c8) when a binding needs to be referenced from an expression. However, this turns out to be really fragile because all residual functions have yet to be fully processed. The normal referentializer process doesn't work here.

I believe that this inherently is incompatible with lazy initialization of these bindings which is why I asked for an option like simple closures #1228.

I suspect the solution to this needs to disable lazy initialization of such bindings since they will always initialize eagerly. At the very least they *might* be initialized eagerly, depending on if an abstract conditional branch touches it.

**Comment by NTillmann** [comment]
Let's see if I understand...

Let's make your example a bit more involved:
```js
(function() {
  var x = 0;
  callThis(function() { x++; });
  global.x1 = x + 1;
  callThis(function() { x++; });
  global.x2 = x + 1;
})();
```

After each call to `callThis`, the value of `x` is unknown, and we'd have to make up a new temporal abstract value whose generator entry reads the referentialized `x`, and stores that in the binding.

Does that match what you want to achieve?

**Comment by NTillmann** [comment]
Another example...

```js
(function() {
  var x = 0;
  callThis(function() { x++; });
  global.x1 = x + 1;
  callThat();
  global.x2 = x + 1;
})();
```

Is `callThis` allowed to store the function, and can `callThat` invoke it again? If so, the set of potentially mutated bindings is getting bigger for every call.

**Comment by NTillmann** [comment]
To deal with this...
- We'd need to figure out at interpretation time which bindings a function captures. Shouldn't be too hard to move around when `ClosureRefVisitor` is called, and caching the result.
- We need to be able to emit a "reading from a referentialized binding" generator entry. As @sebmarkbage observed, this is tricky as the whole referentialization thing happens rather late, after all the generators have been processed. The easiest might be to first emit some kind of placeholder babel node, and later patch it up once the expression to read a referentialized value is known.
- We'll have to proactively emit all those generator entries, but we can mark them as "pure", and then the visitor will remove all those entries whose results are not used.

Regarding lazy initialization... Yeah, it's probably best to just disable that for exactly those referentialized binding that are referenced by the reading-from-a-referentialized-binding generator entries. There might potentially be a benefit to keep them lazy as `callThis` call might be in a conditional generator.

**Comment by NTillmann** [comment]
Great!

What I mean is, immediately after a call to `callThis` the interpreter won't know which bindings will be read later on. So we must emit reading-from-referentialized-binding generator entries for all bindings which at that point are known to have been referentialized.

**Comment by NTillmann** [comment]
Thinking about it, another little issue: Conditional branching complicates things a bit. Along different branches, different bindings might have leaked. Ideally, that set needs to get tracked as part of the `Effects`, and participate in joins. We might not do that and instead just keep a static set around that simply grows. However, that could theoretically lead to suboptimal reasoning / code, as we'd turn some perfectly concrete values into abstract ones along some paths.

**Comment by hermanventer** [comment]
I'm a bit freaked out about this. The fundamental assumption of Prepack is that we know the whole program. The environment is a bit special, but we assume that the model tells us everything we need to know.

With this discussion, we are entering a whole new dimension and there be dragons.

The only viable tactic that comes to mind right now is that we should treat local variables that leak out to the environment as if they are intrinsic properties of the global object.

**Comment by sebmarkbage** [comment]
Both of your comments are addressed in #1142. Looks like it is time for another review. :)

**Comment by yinghuitan** [comment]
For "lazy initialization" concern, I do not think it will be an issue if we have a generator entry that can serialize the leaked bindings. Because visitor's scope analysis will report this binding being referenced both from residual function(callThis()) and global code(the leaked binding generator entry), it won't be delay initialized.

**Comment by NTillmann** [comment]
I think we have everything that's needed now with the concept of leaked bindings.
