### ISSUE TITLE
Incorrect sharing of bindings of residual/additional functions

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#1250]
```javascript
let x = undefined;
let y = undefined;
let z = undefined;
global.f = function() {
    x = {};
}

global.f1 = function() {
    y = {};
}
global.f2 = function() {
    z = {};
}

__optimize(f);
```
Prepack produces
```javascript
(function () {
  var _0 = function () {
    var _1 = {};
    _2 = _1;
  };

  var _3 = function () {
    _2 = {};
  };

  var _4 = function () {
    _2 = {};
  };

  let _2 = void 0;

  f = _0;
  f1 = _3;
  f2 = _4;
})();
```

The variables `x`, `y`, `z` all get erroneously collapsed into `_2`. Possibly has to do with common subexpression elimination? Needs further investigation. 

@hermanventer any ideas?

**Comment by hermanventer** [comment]
CSE should not treat two distinct objects as interchangeable, even if they are structurally identical. If it does, that is a bug.

**Comment by NTillmann** [comment]
Fixed by referenced pull request.
