### ISSUE TITLE
Extend types domain to track integral numbers

### ISSUE THREAD

**Issue by hermanventer** [facebook/prepack#1269]
Adding two integral numbers results in an integral number (although not necessarily something that can be stored in a machine integer representation). Likewise for various other operations. If the types domain were to track whether a numeric value is integral, this can be combined with a Range domain to discover values that can be represented in 32-bit integers, and so on. Eventually, this can be communicated to the runtime. Right now, it can be used to make the Abstract Interpreter more precise when dealing with array element assignments, particularly inside loops.

The Types domain is built on top of the Value class and its subclasses. This means that you have to add a subclass of NumberValue, probably named IntegralValue. This may break some unsafe assumptions about the .getType() results of values, so be sure to check every place where something like x.getType() === NumberValue happens (if any). In general, we need to move away from checking the value of getType() directly and instead add relevant "isXXX()" predicates on Value so that we can potentially use multiple domains to answer such questions.

Within TypesDomain.js itself, the main work is to adapt the transfer functions to produce Integral types when appropriate.

**Comment by NTillmann** [comment]
@hermanventer, is #1337 addressing this issue entirely, or is there anything left to do?

**Comment by hermanventer** [comment]
I think it is done.
