### ISSUE TITLE
saya tidak bisa membuka fb saya bagaimana caranya

### ISSUE THREAD

**Issue by gustrimerdeka90** [facebook/prepack#1312]
https://m.facebook.com/recover/code?ph%5B0%5D=%2B%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A22&rm=send_sms&src_flow=skip_initiate&hash=AUZf1dC1sfdUcvmd&ref=opera_speed_dial&_rdr

**Comment by hermanventer** [comment]
Looks like spam.

**Comment by gustrimerdeka90** [comment]
lalu bagaimana saya biyar saya bisa membukanya lagi.. apa kah ada link nya
