### ISSUE TITLE
Lots of empty statements with recursive code, and erroneously missing globals.

### ISSUE THREAD

**Issue by isiahmeadows** [facebook/prepack#1333]
Tried running the example from #543 [on the website](https://prepack.io/repl.html#BQMwrgdgxgLglgewsAlAAgN4Cg1vNeJPOAI2AA91tdcAbAUxjQE80BeNAEQEMZ6A6CAgDuqANxoA9JLQwAFvTRgAzvQbLlaWnAiL5vNAEk03ACan6pnDQBOjMDYhpyaADwcAjGgD8ztAC5iMhcAWjQPdABqIIo0MIAmFDFrAF8sawYmFw4ePkERcWs4EDRYgCo0eLQAPjQAFkS-DhBSYA8ABiTrAHNaBBJuWn47ZTBaJg5yZJSUcSA):

```js
(function() {
  function fib(x) {
    let y = Date.now(); // the useless line that I added
    return x <= 1 ? x : fib(x - 1) + fib(x - 2);
  }

  let x = Date.now();
  if (x * 2 > 42) x = fib(10);
  global.result = x;
})();
```

and I ran into this interesting oddity:

<details>
<summary>Click to show</summary>

```js
(function () {
  var _$2S = this;

  var _$0 = _$2S.Date.now();

  var _1 = _$0 * 2;

  var _0 = _1 > 42;

  {
    if (_0) {
      {
        {
          {
            {
              {
                {
                  {
                    {
                      {
                        {}
                        {}
                      }
                      {}
                    }
                    {
                      {}
                      {}
                    }
                  }
                  {
                    {
                      {}
                      {}
                    }
                    {}
                  }
                }
                {
                  {
                    {
                      {}
                      {}
                    }
                    {}
                  }
                  {
                    {}
                    {}
                  }
                }
              }
              {
                {
                  {
                    {
                      {}
                      {}
                    }
                    {}
                  }
                  {
                    {}
                    {}
                  }
                }
                {
                  {
                    {}
                    {}
                  }
                  {}
                }
              }
            }
            {
              {
                {
                  {
                    {
                      {}
                      {}
                    }
                    {}
                  }
                  {
                    {}
                    {}
                  }
                }
                {
                  {
                    {}
                    {}
                  }
                  {}
                }
              }
              {
                {
                  {
                    {}
                    {}
                  }
                  {}
                }
                {
                  {}
                  {}
                }
              }
            }
          }
          {
            {
              {
                {
                  {
                    {
                      {}
                      {}
                    }
                    {}
                  }
                  {
                    {}
                    {}
                  }
                }
                {
                  {
                    {}
                    {}
                  }
                  {}
                }
              }
              {
                {
                  {
                    {}
                    {}
                  }
                  {}
                }
                {
                  {}
                  {}
                }
              }
            }
            {
              {
                {
                  {
                    {}
                    {}
                  }
                  {}
                }
                {
                  {}
                  {}
                }
              }
              {
                {
                  {}
                  {}
                }
                {}
              }
            }
          }
        }
        {
          {
            {
              {
                {
                  {
                    {
                      {}
                      {}
                    }
                    {}
                  }
                  {
                    {}
                    {}
                  }
                }
                {
                  {
                    {}
                    {}
                  }
                  {}
                }
              }
              {
                {
                  {
                    {}
                    {}
                  }
                  {}
                }
                {
                  {}
                  {}
                }
              }
            }
            {
              {
                {
                  {
                    {}
                    {}
                  }
                  {}
                }
                {
                  {}
                  {}
                }
              }
              {
                {
                  {}
                  {}
                }
                {}
              }
            }
          }
          {
            {
              {
                {
                  {
                    {}
                    {}
                  }
                  {}
                }
                {
                  {}
                  {}
                }
              }
              {
                {
                  {}
                  {}
                }
                {}
              }
            }
            {
              {
                {
                  {}
                  {}
                }
                {}
              }
              {
                {}
                {}
              }
            }
          }
        }
      }
    }
  }

  var _5 = _0 ? 55 : _$0;

  result = _5;
}).call(this);
```
</details>

Note that if you remove the `Date.now()` in `fib`, the problem disappears. So I suspect it's related to #543.

Also, as a side note, [it's erroneously believing `module` and `require` don't exist in Node](https://prepack.io/repl.html#BQMwrgdgxgLglgewsAlAAgN4Cg1oERgDOApmoTAE5yx4DcOa408SjcARsAB7ra64ViARzBxBwPCAQI8KevzSCYYChDRc0AHgC8aAIxoA-OrQAuNpw0BafegDUF7mhsAmOQwC+DBgBtiME10AEQBDGGIAOggEAHdUeTQ4EDQnACo0FzQAPjQAFjdAxz0ABndcAFsEABMwPwjiLgAHBAoYQjRdLnoPFHigA).

**Comment by hermanventer** [comment]
Prepack mostly supports ES5 only at the moment since the main scenarios at Facebook happen after Babel has lowered the code to ES5. Hence there is currently no support for module and require.

**Comment by isiahmeadows** [comment]
Just as a heads up, `let` could be swapped for `var` without change. Also, note that `module` and `require` are CommonJS-specific, and have nothing to do with ES6+.

Here's another thing: if I replace `require` with `console.log`, [it still generates the unnecessary blocks](https://prepack.io/repl.html#BQMwrgdgxgLglgewsAlAAgN4Cg1vNeJPOAI2AA91tdcA3AQwCc0BPNAXjSiQGcEAbAKYA6fggDmqANxoA9LLQwAFoLRgegoTx5p+cCKuX0YaAJJp6AE0uDLOGo0EwwjCGnJoAPJwCMaAPzuaABcxGQeALRoPugA1GEUaFEATChS9gC+WPYMzB6cACLGIhAIAO7S9nAgaIkAVGjJaAB8aAAsqUGcIKTAPgAMafbiYiT0-MKOPGD8Jpzk6Rko0kA), just without erroneously removing the calls.

**Comment by isiahmeadows** [comment]
Just as a heads up, `let` could be swapped for `var` without change. Also, note that `module` and `require` are CommonJS-specific, and have nothing to do with ES6+.

Here's another thing: if I replace `require` with `console.log`, [it still generates the unnecessary blocks](https://prepack.io/repl.html#BQMwrgdgxgLglgewsAlAAgN4Cg1vNeJPOAI2AA91tdcA3AQwCc0BPNAXjSiQGcEAbAKYA6fggDmqANxoA9LLQwAFoLRgegoTx5p+cCKuX0YaAJJp6AE0uDLOGo0EwwjCGnJoAPJwCMaAPzuaABcxGQeALRoPugA1GEUaFEATChS9gC+WPYMzB6cACLGIhAIAO7S9nAgaIkAVGjJaAB8aAAsqUGcIKTAPgAMafbiYiT0-MKOPGD8Jpzk6Rko0kA), just without erroneously removing the calls.

**Edit:** [Here's a smaller test case.](https://prepack.io/repl.html#BQMwrgdgxgLglgewsAlAAgN4Cg1vNeJPOAI2AA91tdcokBnBAGwFMA6JhAc1QG4cacEGgroQpCmgC0aAIwp+uAL5YBAejVoASiwC2CAG4s0MABbGW5GCwBOEAIZM0dCABM4hCABo09t2g80AHcEGwBrel9IywAHFlgWVwEhEQARe2s2CAQg1DEJWQAGBSwlFD4gA)

**Comment by hermanventer** [comment]
Prepack has no builtin knowledge of the Node object model. That has to be provided via an explicit model that is supplied to Prepack just like any other source file.

We use var instead of let because some environments we care about still do not support let. There are also other reasons that may come into play in the future as code gets moved around and issues like #1266 get fixed.

**Comment by isiahmeadows** [comment]
@hermanventer The first sentence of my last comment was mentioning that `var`/`let` was out of scope of this bug. I was just stating it was immaterial.

**Comment by hermanventer** [comment]
Removing the calls to Date.now() seems perfectly OK since they have no side effect on the global heap and their results are not used. Keeping the block structure, as in the second test case, is not strictly necessary, but removing it does not seem particularly compelling. Keeping nested empty blocks, however, is just annoying.
