### ISSUE TITLE
Set/Map constructor with parameter incompatible with JSC should emit compile time error instead of runtime 

### ISSUE THREAD

**Issue by yinghuitan** [facebook/prepack#1340]
Example:
https://github.com/facebook/prepack/blob/dd8c39ee19783226d8f5ccd7a36023bf799437da/src/intrinsics/ecma262/Set.js#L46

It should be a compile time error instead of runtime which is much harder to troubleshoot.

**Comment by NTillmann** [comment]
But even if it's unrelated to JSC, it's generally a bad idea to silently generate code that unconditionally throws an exception along the global code.
