### ISSUE TITLE
Support for nested additional functions

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1398]
I need something like the following to work:

```js
(function() {
    function render1() {
    	function render2() {
            return 1 + 2; // This should get prepacked!
	}
        __optimize(render2);
	return render2;
    }

    __optimize(render1);

    global.render1 = render1;
})();
```

**Comment by NTillmann** [comment]
#1626 lists many more test cases that should be made to work...

**Comment by cblappert** [comment]
I think at this point all of those test cases are part of `additional-functions/` tests except for a few that deal with mutation we don't intend to support.

**Comment by cblappert** [comment]
Test case works in online repl.
