### ISSUE TITLE
__abstract() errors should be compile time instead of runtime

### ISSUE THREAD

**Issue by yinghuitan** [facebook/prepack#1404]
Reproduce:
Try to prepack the following code:
```js
__assumeDataProperty(this, "object test", __abstract("{p: 100}", "object literal"));
```
Note: the first parameter passing to __abstract is quoted with a string instead of template object.

Result:
PrePack succeeds but emits a runtime error.

Expect:
Compile time error.

**Comment by kedromelon** [comment]
interested in helping out here. having trouble reproducing though -- is more context needed? i seem to be seeing a compiletime TypeError in the repl: https://prepack.io/repl.html#PrCGGdwVwWwUwCKgC6gAoCcD2AHOHkBPACmQAsBLcAGgAIAiLAIwCs4BjZW5OcZeuiFBM+GUJ2L0A3jgBctAIwAGJQF8BDZm060ANhR5jd9AJQmA3ACggA

**Comment by hermanventer** [comment]
This seems to be a special case of a more general problem that has been fixed already.
