### ISSUE TITLE
Clarify makeSimple() lifetime

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1457]
The way `makeSimple()` works is that by default is that it does a lazy check on the properties, but if it can't (partial or abstract), it falls back to a flag. The flag is `false` at first but we can force it to be `true` by calling `makeSimple()`. Once we set it to `true` we currently never “demote” it.

Consider this case:

```js
(function() {
  var x = {};
  var y = 0;

  __makeSimple(x);
  Object.defineProperty(x, 'foo', { get() { y++ } }); // this introduces a lie

  Object.assign({}, x); // thinks x is simple because we claimed so
  global.result = y; // incorrectly emits 0, should've been 1
})();
```

We currently only proceed with partial sources in `Object.assign` if they're also simple:

https://github.com/facebook/prepack/blob/a09d939a42e9225ae61ed405d81efc33609bfdaa/src/intrinsics/ecma262/Object.js#L83-L89

In my example, we first claimed `x` was simple, but then we put a getter on it. So that confused `Object.assign`. This seems like a problem.

In practical scenarios, of course, it’s silly to `__makeSimple()` and then `defineProperty` on it. But it’s necessary for cases like https://github.com/facebook/prepack/pull/1456 where I want to programmatically claim that an object I made a partial *is* simple, at least *it is right now*. In other words, **I converted it to a partial but I claim that I know this hasn’t changed its simple-ness. I don’t claim to know what happens to it later though (and somebody might add a getter/setter to it afterwards).**

I can see two potential ways to go from here:

1. Treat `_isSimple` as a flag that describes the *current* situation. Invalidate it whenever we lose the confidence. Say, if `Object.defineProperty` is called with a getter/setter. This way, `makeSimple()` is useful and generally safe to call.

2. Treat `makeSimple()` as an instruction that the object is guaranteed to never ever get a getter/setter *even in the code we’re aware of*. In that case `makeSimple()` is almost never safe to call because you don’t really know what’s gonna happen to the object in the future. Maybe we should throw if you attempt to define a property on such object (instead of silently introducing an inconsistency in its reported and actual “simplicity”). We’ll also need some other way to get the test in https://github.com/facebook/prepack/pull/1456 passing (which is important to us).

**Comment by hermanventer** [comment]
__makeSimple() is a modeling function for objects obtained from the environment. In general, modeling functions are not expected to ever show up in real code. We also cannot allow getters and setters to leak to native code via objects since it will be all too easy for the native code to inadvertently call them, which could modify the global state in ways that Prepack cannot track.

Consequently, option 2 seems to be the only way to go from here.

**Comment by gaearon** [comment]
Do you think this means https://github.com/facebook/prepack/pull/1456 is the wrong/dangerous fix?

Something was calculated-simple, then we called `Object.assign` with it as a target, then it becomes partial *and* flagged-simple, then we put a property on it. Now it's wrongly tagged as simple.

I'm struggling to come up with a scenario where this matters. Can you give me some example where assuming an object is simple (but it's not) actually introduces a bug?

**Comment by hermanventer** [comment]
I don't think #1456 is wrong or dangerous. I do, however, think that any attempt to modify an object, which has the __isSimple flag set, in way that will invalidate the flag, should result in a compilation error. If the object is not reachable from the native environment, nothing bad could happen, but if it is, there might be code running at runtime that has effects that Prepack did not take into account.

**Comment by hermanventer** [comment]
To write a failing test case, you probably need to use the // add at runtime: feature. That allows the test to run code that Prepack is unaware of.

**Comment by gaearon** [comment]
>I do, however, think that any attempt to modify an object, which has the __isSimple flag set, in way that will invalidate the flag, should result in a compilation error.

Doesn't this mean that, combined with #1456, this should be a compile error?

```js
var obj = global.__abstract && global.__makePartial && global.__makeSimple ? __makeSimple(__makePartial(__abstract({}, "({foo:1})"))) : {foo:1};

var x = {};
Object.assign(x, obj); // will mark x as flagged-simple

Object.defineProperty(x, 'foo', { get() {} });
```

I think it's pretty unintuitive that calling `Object.assign` on something forbids defining properties on it later. Although it might not be that common of a pattern so it's probably not a blocker for us.

What do you think?

**Comment by hermanventer** [comment]
In this case the object is not reachable from native code, so forbidding the property definition seems a bit onerous. You would, however, have to clear the flag, leaving the object both partial and bereft of any known property other than 'foo'. That would be pretty onerous too. So you get to pick your poison, but you die all the same.

**Comment by hermanventer** [comment]
No further action seems indicated at this moment.
