### ISSUE TITLE
Nomination approval for React Open Source Awards

### ISSUE THREAD

**Issue by operatino** [facebook/prepack#1470]
Hi Prepack team.

Sorry for messaging you through issues, but I didn't managed to find public contacts of project authors and core contributors.

React ecosystem success is entirely built on top of it's open source community and all the enthusiastic developers contributing with their code, ideas, and projects. To give an extra credit to hard working open source developers, together with React Amsterdam Conference, we're launching a first React Open Source Awards (eg Oscars for developers).

Together with a programme committee of 15 people, including active React users and open source contributors, we've came up with 5 award groups, and up to 4 selected nominees per each group, where this project is also nominated amongst the others.

Before we proceed to voting with our jury, we're reaching out projects to make sure there's no objections in participation in such awards. Please let us know if you have any questions about the awards, and if somebody of project authors could visit Amsterdam on April 13, contact hi@react.amsterdam for details.

**Comment by NTillmann** [comment]
Thanks a lot for considering us for a nomination! That is already quite an honor. However, for this year, please skip the Prepack project for nominations. There's still a lot of churn and active ongoing work to define the direction of where the project is going. 

We'd be happy to be considered again next year!
