### ISSUE TITLE
Investigate Memory Usage of Prepack

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#1498]
On large internal test cases, Prepack is using >8gb of memory. We should spend some time investigating why Prepack requires so much memory and how we can reduce it.

**Comment by NTillmann** [comment]
I did that recently; #1783 and #1776 significantly reduced memory usage by 2/3, also resulting in a speedup around 20%. #1782 provides new fine-grained statistics on which passes use how much memory.
