### ISSUE TITLE
base62 package dependency

### ISSUE THREAD

**Issue by rafaelmlourenco** [facebook/prepack#1503]
Hi everyone.

Currently prepack has a dependency (base62) that calls Google Analytics and sends some user data.
Is there any way to prevent this? (E.g. use another npm package?) 
This has yet another problem: when npm installing, some build servers do not have permissions to access google analytics. And, in such case, the installation will fail.

**Comment by NTillmann** [comment]
We don't have to use the base62 package. (In fact, any other encoding would do.) I put out a pull request that would remove the dependency: #1504.

**Comment by NTillmann** [comment]
Addressed by merged pull request #1504.
