### ISSUE TITLE
Widening empty or undefined?

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#1554]
This line seems odd.

https://github.com/facebook/prepack/blob/84887ba29d59379b14185cb4a4ef61fba3e86078/src/methods/widen.js#L184

Why is one empty and the other undefined if there is a missing value?

If I understand this correctly, there shouldn't be a difference between where you put something as v1 or v2. They should both be modeled as empty in the case that they exist in one branch but not the other.

I don't know if this path can ever happen atm but we should probably decide what it should do.

**Comment by hermanventer** [comment]
It does seem that both sides should be empty and, clearly, we need a test case for this.
