### ISSUE TITLE
`Array` instead of `new Array` or `[]`

### ISSUE THREAD

**Issue by kurtextrem** [facebook/prepack#1557]
The output of Prepack uses the `Array(N)` syntax instead of `new Array(N)` or `[]`. 
Both of the latter ones are the ones which are to be preferred, as they come with higher perf (source: https://twitter.com/albertonarda/status/961555559681019904)

I'd link to a test case, but the repl seems broken atm. I get
```
undefined
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
```
even on example code.

**Comment by NTillmann** [comment]
There's indeed something not working on the repl (I filed #1558 for that), but it's not all broken...

Anyway, repl or not, do you have a repro where you'd like Prepack to generate different code?

**Comment by kurtextrem** [comment]
The code where I have observed this, is here: https://github.com/kurtextrem/Twitch5/blob/master/worker.js

Before prepacking, replace this line: https://github.com/kurtextrem/Twitch5/blob/master/worker.js#L12 with `const ВЕРСИЯ_БРАУЗЕРА = 60`

Why I created this issue, see here (it's minified and... the REPL doesn't work as I said so I can't show you the unminified result): https://github.com/kurtextrem/Twitch5/blob/master/worker_pre.js

```javascript
"use strict";
var Проверить,Браковать,ЗавершитьРаботуИПоказатьСообщение,ЗавершитьРаботуИОтправитьОтчет,ВыброситьВПомойку,ОкруглитьРазмерКучиAsmJS,AsmJS,ПотокБитов,IsoBaseMedia,ID3,Срез,СрезОбработки;

(function(){var t=Array(2),
```

Prepack creates a new variable and initializes it with `Array(2)` why and what for is unknown to me, but see OP why `new Array(2)` should be preferred 
(I think `[]` is even better as this is probably used for array operations, not to optimize initiation - but that's up to you guys as Prepack is for optimization initiation?)

**Comment by NTillmann** [comment]
I've looked a the performance implications, and it doesn't seem to make any noticable difference. I am closing the issue for now, but happy to take another look if there's a real-world benchmark where the prepacked code is measurably suboptimal.

**Comment by kurtextrem** [comment]
@NTillmann Out of curiosity, what/how did you bench?
