### ISSUE TITLE
Serialization issue with optimized functions

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#1571]
If you use the following input, you'll see many issues with the serialzied output, with variables never declared and some never used:

```js
(function() {
  function func(props) {
    var _ref2;
    var commentsByID = {};
    var edges = Array.from(
      ((_ref2 = props.feedback) != null
        ? (_ref2 = _ref2.top_level_comments) != null ? _ref2.edges : _ref2
        : _ref2) || []
    ).reverse();
    edges.forEach(function(_ref5) {
      var node = _ref5.node;
      if (node && node.id) {
        commentsByID[node.id] = node;
      }
    });
    return { commentsByID: commentsByID };
  }
  
  __optimize(func);
  
  window.result = func;
})();
```

**Comment by cblappert** [comment]
Looks like what's happening is that the `initializationStatements` of the nested function are not getting emitted to the correct location. Looking into how to fix it now.

**Comment by cblappert** [comment]
So what's happening here is the leak logic is putting into the additional function's generator an emitBindingAssignment for commentsByID when it's accessed from the anonymous function. This makes the additional function think that it is capturing the binding from a parent scope and is causing the initializer to be emitted in the parent scope of the additional function.

Let me think about this a bit and I'll try to put up a PR later.

**Comment by NTillmann** [comment]
Running the code through Prepack gives me with the following message.
```
Errors found while prepacking
In input file /tmp/test.js(8:45) FatalError PP0001: This operation is not yet supported on abstract value props  (https://github.com/facebook/prepack/wiki/PP0001)
    at from (native)
    at func (/tmp/test.js:5:21)
```

(And it also produces a rewritten dubious program.)
Is the error + output expected?

**Comment by trueadm** [comment]
@NTillmann you are probably misssing a pure wrapper. Optimized functions used to all be pure with the node enabled.

**Comment by NTillmann** [comment]
Here's a somewhat minimal repro, even though it also first seems to fail with "RecoverableErrors":
```js
(function() {
  function f(g) {
    var x = {p: 42};
    g(function() { x = {p: 23}; });
    return x;
  }
  if (global.__optimize) global.__optimize(f);
  global.inspect = function() { return f(function() {}).p; }
})();
```

**Comment by NTillmann** [comment]
It seems to all work now; the only variable that are not used are those involved in abstract function calls, but I feel that's not a serialization issue, but something that probably should be encoded differently early during abstract interpretation.

@trueadm, can we close this issue?
