### ISSUE TITLE
Should support abstract key access on abstract object

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#1584]
Should support unary abstract key access by recovering. This case currently fails without recovery:

```js
// abstract effects
x = 0;

__evaluatePureFunction(() => {
  var foo = __abstract();
  var bar = __abstract();

  if (foo.prop[bar]) {
    x = 10;
  } else {
    x = 20;
  }
});
```

**Comment by sebmarkbage** [comment]
Yea, this is the same work as we've done for binary expressions. I'm happy to take that on since I did the last version. Assuming the version that is in place for binary expressions seems to be working.

**Comment by sebmarkbage** [comment]
I removed the unary expression in your example. The unary expression doesn't have anything to do with the core issue which has more to do with unknown property access on a partially known object.

**Comment by trueadm** [comment]
@cblappert I'd expect it to throw a FatalError and the we'd recover and emit a temporal with the pure code like we do in other cases.

**Comment by sebmarkbage** [comment]
I’ve been working on a solution. It’s a bit involved give in how many cases we need to bail out for partial values and how prototype chains works but we’ll get there.

**Comment by trueadm** [comment]
@sebmarkbage Any luck on this? It's common to run into this invariant, related to this issue I believe, and it causes the compilation to completely die:

https://github.com/facebook/prepack/blob/master/src/values/AbstractObjectValue.js#L485

**Comment by trueadm** [comment]
I believe this is a related fix: https://github.com/facebook/prepack/pull/1651

**Comment by hermanventer** [comment]
Is this still an issue?

**Comment by trueadm** [comment]
I believe not.
