### ISSUE TITLE
Use before definition 

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1585]
When evaluating the following with --abstractEffectsInAdditionalFunctions
```js
// abstract effects

var __evaluatePureFunction = this.__evaluatePureFunction || (f => f());
let props = global.__abstract ? __makeSimple(__abstract('object', '({ profile: { id: 123 } })')) : { profile: { id: 123 } };

let x;
function foo() {
    if (props.profile) return;
    if (props.profile.id) return;
}
__evaluatePureFunction(() => {
        x = foo();
    });

inspect = function() {
    return x;
}
```

an invariant in the serializer triggers. When disabling the invariant, we get the following code.
```js
var foo;
(function () {
  var _$3 = this;

  var _0 = function () {
    if (_1.profile) return;
    if (_1.profile.id) return;
  };

  var _6 = function () {
    return _7;
  };

  var _1 = {
    profile: {
      id: 123
    }
  };
  _$3.foo = _0;
  {
    var _$0 = _1.profile;

    if (!_$0) {
      if (!_$2) {
        var _$1 = _1.profile;
        var _4 = _$1;
        var _$2 = _4.id;
      }
    }
  }

  let _7 = void 0;

  inspect = _6;
}).call(this);
```

It seems that `_$2` is defined in a conditional block guarded by `_$2` itself. Doesn't make sense.

**Comment by sebmarkbage** [comment]
Your pure function isn't pure.

We should add errors if you try to mutate a non-newly created thing if we're isInPureScope.

Can we please start writing tests and examples in terms functions that return values instead of mutating so that they won't break when we add that? Also, who know how the system behaves if they're not pure.

**Comment by NTillmann** [comment]
@sebmarkbage, you are right, there is a purity issue in this example. But that's not the point. The bug also triggers with the slight rewrite into
```js
x = __evaluatePureFunction(() => {
        foo();
    });
```

So we should add that, or a variation that calls `__optimize`, when persisting this in our test suite.

**Comment by hermanventer** [comment]
A purity checker will be very useful here. It is not a trivial project. Perhaps a suitable project for an intern?

**Comment by sebmarkbage** [comment]
@hermanventer I'm suggesting some simpler.
```js
Set(...) {
  if (realm.createdObjectsTrackedForLeaks && !realm.createdObjectsTrackedForLeaks.has(this)) throw new FatalError();
  ...
}
```
