### ISSUE TITLE
Issue warnings or errors if a pure function is mutating outer scopes

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#1589]
In a pure function we assume that we don't mutate anything in the outer scope. We should probably issue a fatal or at least a warning if can prove that this assumption is incorrect.

I.e. if we're mutating a non-newly created closure or object.

We can't always detect all cases where this can happen because unknown abstract functions could be mutating something but we should at least enforce it as much as we can.

**Comment by cblappert** [comment]
#2175 addresses this
