### ISSUE TITLE
Serialization bug, emitting entries to wrong scope body

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#1620]
This issue requires PR – https://github.com/facebook/prepack/pull/1613 to be applied locally before running the below example:

Given the following example:

```js
(function() {
  function Foo(props) {

    function bar() {
      return props.foo;
    }

    return <div ref={bar}>{props.text}</div>
  }

  __optimizeReactComponentTree(Foo);

  global.Foo = Foo;
})();
```

The output is incorrectly:

```js
(function () {
  var _0 = function (props) {
    /*Additional function generator*/var _$0 = _1.text;

    var _2 = <div ref={_4}>{_$0}</div>;

    return _2;
  };

  var _4 = function () {
    /*Additional function generator*/var _$2 = _1.foo;
    return _$2;
  };

  Foo = _0;
  var _1 = props;
  var _1 = props;
})();
```
The `var _1 = props;` entries have been added to the main body rather than the optimized function bodies.

**Comment by NTillmann** [comment]
Does look like it captures the essence of what you want? https://github.com/facebook/prepack/blob/dce4a8619faa25f2bac9f50e90c3f228d8d3de5b/test/serializer/additional-functions/NestedOptimizedFunction15.js

**Comment by NTillmann** [comment]
The issue no longer reproduces for me. @trueadm, can we close the issue?
