### ISSUE TITLE
#1712 suppresses valuable error messages

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1762]
I've now ran into a case where I am getting errors with no message because of this. This is on a larger internal test case.

Was there an assumption that those empty messages would never make it to the end-user? That's not the case.

**Comment by hermanventer** [comment]
This is under the control of a flag that you can toggle in your case. The motivation for the flag was to cater for applications where errors are expected and surfacing them to end users is very expensive noise.

**Comment by NTillmann** [comment]
We now have a flag --instantRender to more selectively drive prepack.
