### ISSUE TITLE
Issues around BreakCompletions

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#1764]
I have two test cases here that currently fail with invariants on master. These invariants are both affecting the init path (not the React rendering paths) on internal FB bundles:

Case 1:
```js
var x = global.__abstract ? x = __abstract("number", "(3)") : 3;

function func1() {
  for (let i = 0; i < 10; i++) {
    if (i === x) {
      break;
    }
    if (i === 4) {
      throw new Error("This should not happen");
    }
  }
}

if (global.__optimize)
  __optimize(func1);
```

Case 2:

```js
if (global.__abstract) x = __abstract("number", "(3)");

function func1() {
  let i = 0;

  while (i++ < 10) {
    if (i === x) {
      break;
    }
  }
  return x;
}

if (global.__optimize)
  __optimize(func1);
```

**Comment by NTillmann** [comment]
@hermanventer, in your referenced pull request, you said that you addressed the first case. But I just tried the second case on master, and it also produces good code (I think). Is there anything else you want to do here, or is this done?

**Comment by hermanventer** [comment]
I forgot that the second case is turned into a for loop under the covers.
