### ISSUE TITLE
Invariant when handling of PossiblyNormalCompletion

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#1767]
I couldn't reduce this any further, this is still a React test, so make sure React mode is enabled:

```jsx
function App(props) {
  if (props.x) {
    throw new Error("I am an error");
  }
  return 123;
}

__optimizeReactComponentTree(App);
```
It results in the invariant:

`Invariant Violation: an abstract value with an identifier "_$0" was referenced before being declared`

**Comment by hermanventer** [comment]
This appears to be the same issue as #1766.
