### ISSUE TITLE
Bad code generation when optimized function mutates object created in outer scope

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1789]
Prepacking
```js
(function () {
  let outer = {};
  function f(x) {
    outer.x = x;
    return outer;
  }
  __optimize(f);
  global.f = f;
  inspect = function() { return f(42).x; }
})();
```
results in the following:
```js
(function () {
  var _0 = function (x) {
    var _1 = x;
    _3.x = _1;
    return _3;
  };

  var _4 = function () {
    return _0(42).x;
  };

  var _3 = {
    x: _1
  };
  f = _0;
  inspect = _4;
})();
```

Note the reference to `_1` in the definition of `_3`, which is clearly wrong.

**Comment by hermanventer** [comment]
This may be related to https://github.com/facebook/prepack/issues/1766

**Comment by NTillmann** [comment]
@hermanventer , I don't think this is the same issue.

This issue represents to me a big whole in the current serializer design: It does not proper apply generator effects when optimized functions refer to values that come from outer scopes.

I am working on this...
