### ISSUE TITLE
Invariant in React reconciler: AbstractValue.createFromConditionalOp() may return NullValue

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1792]
I haven't worked on reducing this yet but filing in case the fix is obvious.

This invariant fails:

https://github.com/facebook/prepack/blob/de5232759323bdd3704af057db8d5af8fb851a2d/src/react/reconcilation.js#L924

Specifically, `abstractValue` can be a `NullValue` if both `left` and `right` are `NullValue`.

**Comment by hermanventer** [comment]
This happens because of simplification. You can turn that off with an optional argument to createFromConditionalOp. Since simplification is a "Good Thing (TM)", it also bears asking "Why has value not been simplified before calling _resolveAbstractValue?".

**Comment by trueadm** [comment]
If we can get a repro case for this, I think I have a good idea how to fix it.

**Comment by trueadm** [comment]
I believe this should be fixed with #1807 too.
