### ISSUE TITLE
Improve code generation in presence of exceptions

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1870]
This test case works, 
```js
(function () {
    var c = global.__abstract ? __abstract("boolean", "(false)") : false;
    inspect = function() { return 42; }
    if (c) throw new Error();
})();
```

but generates suboptimal code.
```js
(function () {
  var $$0 = {
    enumerable: false,
    configurable: true,
    writable: true
  };

  var _$0 = this;

  var _$1 = _$0.Error;
  var _$2 = _$1.prototype;
  var _$3 = _$0.Object;
  var _$4 = _$3.defineProperty;

  var _4 = function () {
    return 42;
  };

  var __constructor = function () {};

  inspect = _4;
  var _0 = false;
  var _3 = _$2;

  var _1 = (__constructor.prototype = _3, new __constructor());

  $$0.value = "Error\n    at test/serializer/basic/PPP.js:4:18\n    at test/serializer/basic/PPP.js:1:1", _$4(_1, "stack", $$0);
  if (_0) throw _1;else ;
}).call(this);
```

Maybe there's more than one thing suboptimal. For the purposes of this issue, my concern is that the exception `_1` is always constructed, even when it's not thrown.

This currently happens via `emitConditionalThrow`:
https://github.com/facebook/prepack/blob/72994a6851015eed49cc5c239eae907af4193601/src/utils/generator.js#L656

It creates on generator entry that conditionally throws and depends on all exception values. When different exceptions can be thrown, e.g.
```js
(function () {
    var c = __abstract("boolean", "(c)");
    var d = __abstract("boolean", "(d)");
    var e = __abstract("boolean", "(e)");
    if (c) throw new Error();
    if (d) throw new Error();
    if (e) throw new Error();
})();
```
Then a statement with a cascade of `if`s is generated:
```js
if (_0) throw _1;else if (_3) throw _4;else if (_6) throw _7;else ;
```

But it's one statement that depends on all exception objects. The serializer cannot look into that statement, and eagerly materializes all these exceptions.

`emitConditionalThrow` should be changed to instead generate nested conditional generators, similar to what happens in `joinGenerators`; in fact, `emitConditionalThrow` should just call `joinGenerators`:
https://github.com/facebook/prepack/blob/72994a6851015eed49cc5c239eae907af4193601/src/utils/generator.js#L1164

And each generator contains just one entry, either the entry that is appended by `joinGenerators`, or the entry that is appended by `emitThrow`.

Then the code generated by the serializer should know create the exception objects within the branches that need them.

**Comment by NTillmann** [comment]
As part of this change, consider refactoring `PossiblyNormalReturnEntry` and `JoinedAbruptCompletionsEntry` into a single `IfThenElseEntry` class.

**Comment by olydis** [comment]
@NTillmann Also combine `emitPossiblyNormalReturn` and `emitJoinedAbruptCompletions` to `emit IfThenElse` or keep the "facade" as is?

**Comment by NTillmann** [comment]
No need to keep the facade.

**Comment by olydis** [comment]
closed via https://github.com/facebook/prepack/pull/1889
