### ISSUE TITLE
Add support for count assertions

### ISSUE THREAD

**Issue by sb98052** [facebook/prepack#1871]
It would be helpful to have an assertion that checks the number of occurrences of a string in generated code. It already seems to be in use here: https://github.com/facebook/prepack/blob/master/test/serializer/abstract/ModifiedBindingsCSE.js

Something like the following?

// count of 42:2

**Comment by NTillmann** [comment]
The test runner indeed checks what's stated in this comment --- it's like an assertion.

Does that do what you want, or do you really want an API for that?

**Comment by sb98052** [comment]
Yes, that does what I was looking for.
