### ISSUE TITLE
List of recommended reading for new contributors

### ISSUE THREAD

**Issue by prometheansacrifice** [facebook/prepack#1887]
Prepack happens to be one of those projects where knowledge of certain areas of computer science (partial evaluation, program specialisation in general, abstract interpretation etc) are vital to understand how things work under the hood. Personally, in the past I have been able to make small contributions to the interpreter, but when it comes to the serialiser, things went over my head.

While the homepage does try to explain how these concepts are put together, a list of recommended reading books/articles would really help. I found [Partial Evaluation: Practice and Theory]( https://www.amazon.in/Partial-Evaluation-Practice-International-Copenhagen/dp/3540667105) to be a great start (of course after Wikipedia). Suggested reading for the theoretical concepts involved would help us a lot.

**Comment by NTillmann** [comment]
I started a wiki page on with suggested reading material:
https://github.com/facebook/prepack/wiki/Suggested-reading

Let me know if that helps, or what areas you'd like more information about.

**Comment by prometheansacrifice** [comment]
Thank you so much :) The wiki was exactly what I had in mind. I'll close this issue for now re-open it if I feel the need for more material.

**Comment by gaearon** [comment]
Should we point to Wiki from somewhere? In my experience Wiki pages aren’t always easy to find. It’s not obvious when a project actually uses the Wiki so many don’t look for it.

I would suggest having a file like CONTRIBUTING.md that points to the relevant resources.

**Comment by prometheansacrifice** [comment]
Fair point. Or a section in the ReadMe.md itself pointing to the Wiki?

**Comment by gaearon** [comment]
I don't think it matters where it is as long as:

* there's a centralized place with links to all contributing docs
* we link to that place from other entry points people might consider (README, Contributing.md, website)

**Comment by gaearon** [comment]
I think it's fine if Wiki home page plays that role, let's just make sure we link to it everywhere.

**Comment by trueadm** [comment]
I think should make a wiki homepage and link to it from the website and the README.md

**Comment by prometheansacrifice** [comment]
Now that the Readme points to the wiki, I think we can close this - at least for now. Feel free to reopen this if there is a need.
