### ISSUE TITLE
Why isn't it an error to mutate a variable read by optimized function from a non-optimized function?

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1891]
I got confused by this example:

```js
(function () {
  var x = 5;

  function getDoubleOfX() {
    return 2 * x;
  };
  
  function setX(newX) {
    x = newX;
  }
  
  __optimize(getDoubleOfX);

  global.getDoubleOfX = getDoubleOfX;
  global.setX = setX;
})();
```

While `setX` is not optimized, I'd expect this to cause a compile error. It's not very intuitive that `getDoubleOfX` just uses the final value of `x` even though `setX` is exists and is exposed.

Is this too hard to enforce, or does enforcing it create other issues for legit patterns?

**Comment by gaearon** [comment]
Also, why is this a limitation at all?

>Prepack can use the heap values that resulted from running the global code, as if they were constants.

Could Prepack havoc `x` so that it is treated as abstract by optimized functions?

**Comment by hermanventer** [comment]
If we havoced everything that is read by an optimized function, we'll probably find it impossible to do any optimizations at all. Right now, we assume that we can only optimize functions that get called after global code has ended, but BEFORE anything else (that might touch what they read) runs.

If we wanted to enforce this automatically, we'd have to analyze every other function under some very pessimistic assumptions. Even then, we'd be very dependent on the assumption that we can analyze ALL of the code that could run. Of course, this means no eval, but it also means that we either have disallow calling a closure that are passed in as parameter, or that we get so pessimistic that we'd have to conclude that EVERY other function can interfere with our optimized function.

**Comment by gaearon** [comment]
Makes sense, thanks for explaining!
