### ISSUE TITLE
Consequent and alternate JoinedAbruptCompletions may have joint created objects

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1902]
Pull request #1901 adds additional invariants that should hold over completions, but they trigger a test failure in test/serializer/additional-functions/EmitPropertyRegressionTest.js. That is concerning. @hermanventer , can you investigate?

**Comment by hermanventer** [comment]
These invariants are not expected to hold.

**Comment by NTillmann** [comment]
Closing for now while keeping #1855 open.
