### ISSUE TITLE
Question about running prepack on non-terminating function call

### ISSUE THREAD

**Issue by VictorHom** [facebook/prepack#1951]
Sorry if this isn't the right forum to ask.

What is the expected behavior of running prepack on the following:
```
(function() {
  let x = 1;
  while (x >= 1) {
    x++;
  }
})();
```

It seems to be stuck (`prepack script.js --out script-processed.js`), which I can understand why since it isn't meant to end, but what should be the expected behavior? Should it throw an error?

**Comment by NTillmann** [comment]
By default, it doesn't terminate (or might eventually run out of memory), but you can configure a timeout e.g. via `--timeout 10` (10 seconds).

The website REPL is configured with a timeout:
https://prepack.io/repl.html#BQMwrgdgxgLglgewsAlAAgN4Cg1oDYCmMaAHmgLxoCMA3DmgO4AWchawZAfJVetrrhIBqIXVwBfLOJSoaQA

However, there seems to a bug in the error processing in the CLI; I filed an issue for that (#1952).
