### ISSUE TITLE
Add a lint rule to debug-fb-www script

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1982]
We need to add a custom ESLint rule that checks against output like this:

```js
var _0 = _1;

// _1 is declared later
var _1 = ...
```

[no-use-before-define](https://eslint.org/docs/rules/no-use-before-define) looks like what we need but seems like it doesn't allow lazy init like

```js
var _1;

function a() {
  var _0 = _1;
}

function b() {
  _1 = 42
}
```

but we **do** consider it valid. So our rule needs to be more specific.

I think this is important because it's hard to isolate and find these issues in big bundles.

**Comment by hermanventer** [comment]
Agreed. The more validation we can do of Prepack output the better.

**Comment by trueadm** [comment]
I think this may be supported already: https://github.com/eslint/eslint/pull/7948

**Comment by gaearon** [comment]
Yep, thank you for spotting. I misread ESLint docs.
