### ISSUE TITLE
Abstract loop termination conditions

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2019]
Consider the following program.
```js
(function() {
  let c = __abstract("boolean", "(c)");
  let l = c ? 1 : 2;
  let sum = 0;
  for (let i=0; i<l; i++) sum++;
  console.log(sum);
})();
```

Ideally, it would prepack to
```js
console.log((c) ? 0 : 1);
```

However, there is a problem. Since #1972, we distribute conditional abstract values. So the condition in the first loop iteration `0<((c)?1:2)` first simplifies to `(c)?(0<1):(0<2)` which immediately simplifies to `true`. Great! However, in the next loop iteration we get `(c)?(1<1):(1<2)` which immediately simplifies to `(c)?false:true` and then `!(c)`. While our interpreter can deal with abstract conditions in various places, e.g. `if`, it doesn't deal with abstract loop conditions: `ToBooleanPartial` throws on abstract values in
https://github.com/facebook/prepack/blob/1cc12c7579d6450b3c124f81a55f2de64216204a/src/evaluators/ForStatement.js#L93
We should improve that, allowing conditional loop iteration executions. Note that in the yet next iteration, the condition will be `2<((c)?1:2)` which eventually simplifies to `false`, so we will stop there.

However, in general, a loop with abstract conditions might easily result in non-terminating Prepack executions due to limited simplification capabilities (hooking up Z3 would help with that #906). So there should be some configurable limit on the number of conditional loop iterations after which Prepack should just give up.

**Comment by trueadm** [comment]
> if, it doesn't deal with abstract loop conditions: ToBooleanPartial throws on abstract values

This is one of the main bail out causes in the React reconciler when running on the internal FB bundle. We should definitely fix this.

**Comment by hermanventer** [comment]
Examples like these can be handled by using the same technique as PR #2173. It is a very specific and limited hack, but if there is real code out there that would work because of it, I can take this on.
