### ISSUE TITLE
Add regression tests for PRs

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2027]
We found bug fixes to several internal problems, with the relevant PRs:  https://github.com/facebook/prepack/pull/2026, https://github.com/facebook/prepack/pull/2025 and https://github.com/facebook/prepack/pull/2024. The issue is that these are somewhat hard issues to repro locally with generic test cases. This issue is a follow up to ensure we definitely add cases for those in the coming weeks.

**Comment by gaearon** [comment]
We cover these by the bundle now. We can extract smaller ones on a case by case basis if we bump into them.
