### ISSUE TITLE
Infinite loop whilst trying to evaluate for-loop logic created by Babel compiling a for-of loop

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2053]
The original loop was a `for-of` loop that [Babel compiles](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABMOcAUAPAlIg3gKEWTgCdE0IEBnKRGKAUwFtE5hEMA6e5qnAokQD0QxJ3GFEAX3xSgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=es2016%2Ces2017%2Creact%2Cstage-2%2Ces2015-loose&prettier=true&targets=&version=6.26.0&envVersion=) to the following output. This currently gets Prepack stuck in an infinite loop:

```js
function fn(x) {
  for (
    var _iterator = x.items,
      _isArray = Array.isArray(_iterator),
      _i = 0,
      _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();
    ;

  ) {
    // ...

    var _ref;

    if (_isArray) {
      if (_i >= _iterator.length) break;
      _ref = _iterator[_i++];
    } else {
      _i = _iterator.next();
      if (_i.done) break;
      _ref = _i.value;
    }

    var item = _ref;
  }
}

global.__optimize && __optimize(fn);
```

**Comment by NTillmann** [comment]
It's a proper infinite loop, and the only way to break out is via an abstract condition followed by a `break` statement.

What I can see us doing here is have a dedicated loop counter, and when Prepack loops around too often, it gives up with a FatalError that can cause a general bail-out or deoptimization elsewhere.

**Comment by trueadm** [comment]
I see an invariant on this issue with master now. Which is a bit worrying, was this from the recent changes @cblappert?

**Comment by trueadm** [comment]
@hermanventer I believe this new invariant we're seeing might be related to some of your recent PRs. With the above test case, this is the invariant we're getting on `evaluateWithAbstractConditional` in `realm.js`:

![screen shot 2018-06-14 at 20 57 30](https://user-images.githubusercontent.com/1519870/41435109-acb934be-7015-11e8-9ac6-1627cbe8b63c.png)
