### ISSUE TITLE
FatalError recovery fallback missing for AbstractValue.throwIfNotConcrete case

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2055]
Given this case:

```js
function fn(props, splitPoint) {
  var text = props.text || "";

  text = text.replace(/\s*$/, "");

  if (splitPoint !== null) {
    while (text[splitPoint - 1] === "\n") {
      splitPoint--;
    }
  }
  return splitPoint;
}

global.__optimize && __optimize(fn);
```

We get a `FatalError` that we don't recover from in pure scope. This is not optimal and we need to handle this case above in some form without bailing out of the entire function.

**Comment by NTillmann** [comment]
Prepack gives up when hitting the loop with the abstract condition.
This is a hard problem.
And there isn't anything to optimize before the loop.
What would you like to happen?

**Comment by trueadm** [comment]
@NTillmann Ideally, if we could give up somehow or "bail-out" and leave the loop constructs as temporals and treat the body of the loop as an optimized function (I believe we already have this code done for loops anyway?). Maybe @sebmarkbage and @hermanventer might know more. At the very least, we should bail out somehow – an infinite loop in Prepack should never occur.

**Comment by NTillmann** [comment]
> infinite loop

Prepack doesn't run forever, but gives up quickly for this abstract loop condition:
```
PP0001 (7:37): This operation is not yet supported on abstract value 
```

But I totally understand the general high-level idea of turning such loops that Prepack cannot deal with into something like an abstract function call.

**Comment by NTillmann** [comment]
@gaearon, why did you mark this as a bug and not an enhacement? Everything is working as expected, and it looks more like a feature request to me.

**Comment by gaearon** [comment]
It's a bug from the React compiler perspective. Normally when some feature is missing we want to "fall back" and either emit different equivalent code, or if it's hard, "step out" of this component and leave it as it was (without evaluation). I don't know enough about React reconciler to tell what the right fix is.

But I consider any valid code that crashes the compiler (instead of just bailing out on a tree) to be a bug.

**Comment by ahmad2smile** [comment]
Ran into this one while just trying on prepack.

**Comment by ahmad2smile** [comment]
Ran into this one while trying prepack. I do think its related to a while loop I got in a saga using `redux-saga` for polling. Oddly enough If I add wait/delay in catch block of saga CRA build show drop in bundle size. Waiting on #2118
