### ISSUE TITLE
Delayed values are not serialized from nested optimized functions

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2056]
This is a React test case for now, as this is something blocking us from using these on our internal bundle:

```js
function Component(props) {
  var _ref8;
  var value = (_ref8 = props.feedback) != null
    ? (_ref8 = _ref8.display_comments) != null
      ? _ref8.ordering_mode
      : _ref8
    : _ref8;

  var items = props.items;
  var collection = Array.from(items).map(function() {
    return <span>{value}</span>
  });

  return <div>{collection}</div>
}

global.__optimizeReactComponentTree && __optimizeReactComponentTree(Component);
```

It hits this invariant:

```js
invariant(this._waitingForValues.size === 0);
```

Note: to reproduce, you need to set `reactOptimizeNestedFunctions` in `debug-fb-www.js` to `true`.

**Comment by gaearon** [comment]
Here is a non-React serializer test case:

```js
(function () {
  function fn(arg) {
    var value = arg.x !== null ? arg.x : 0;

    function fn2() {
      return value;
    }
    global.__optimize && __optimize(fn2);

    return Array.from(arg.arr).map(fn2);
  }

  global.__optimize && __optimize(fn);

  global.inspect = function() {
    return JSON.stringify([
      fn({arr: [1, 2, 3], x: 1}),
      fn({arr: [1, 2, 3], x: null}),
    ])
  };
})();
```

**Comment by trueadm** [comment]
I can try and take a look at this, maybe @NTillmann can give me some pointers before I begin?

**Comment by NTillmann** [comment]
If “nested optimized functions” means what I think it does, then you entering a very undertested and under designed territory. I have no concrete guidance, but would start by building some very basic non-React test cases to systematically document (and test) what your assumptions about what you’d like to work are.

**Comment by trueadm** [comment]
@NTillmann It is indeed that area, we already have React tests working with some subset of nested optimized React functions for a while now. I was wondering why there might be issues in this particular case. The above "non-React" test by @gaearon might help more, so you don't need to know the internals of the React reconciler.

**Comment by gaearon** [comment]
@NTillmann This doesn't use React: https://github.com/facebook/prepack/issues/2056#issuecomment-393625192

**Comment by gaearon** [comment]
I'm removing "high priority" because we know that nested optimized functions were never finished, and while this is nice to have and would help us, it's not actively making code wrong (unlike [other high pri bugs](https://github.com/facebook/prepack/labels/priority%3A%20high) which do).

**Comment by trueadm** [comment]
@gaearon I'm cool with that. Will be good to get those bugs ironed out this half. Nested optimized functions might be a good starter for next half then.

**Comment by trueadm** [comment]
This appears to be fixed on master now. PR up: https://github.com/facebook/prepack/pull/2124
