### ISSUE TITLE
Object.assign bail-outs is causing unecessary havocing

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2064]
Given the below test case:

```js
// does contain:10

function fn(source1) {
  var target = {}
  var usefulStuff = {
    makeNumber() {
      return 5;
    },
  };
  Object.assign(target, source1, usefulStuff);

  return target.makeNumber() + 5;
}

global.__optimize && __optimize(fn);

target = function() {
  return fn({});
}
```

Currently, `Object.assign` will `FatalError` upon encountering a `source` argument passed to it that is an abstract value that is top. This `FatalError` gets thrown and is then caught in `CallExpression.js` where we try to recover. We recover by re-creating the original function call as a temporal generator entry, then we havoc all the arguments for that function. As you can see in the above example, this isn't the best implementation as it's causing `usefulStuff` to havoc unnecessarily.

We should be able to refine the `Object.assign` implementation to recover itself instead of throwing `FatalError` when in pure scope. This will greatly help reduce bloat we're seeing internally on our bundle.

The three places we throw FatalErrors are:

https://github.com/facebook/prepack/blob/master/src/intrinsics/ecma262/Object.js#L81
https://github.com/facebook/prepack/blob/master/src/intrinsics/ecma262/Object.js#L94
https://github.com/facebook/prepack/blob/master/src/intrinsics/ecma262/Object.js#L107

Looking into the logic, we do this because we don't deem the source to be safe to be able continue with the `Object.assign` evaluation, so we `FatalError`. Yet, the recovery emits the exact same `Object.assign` after in pure scope – which means that we're still doing the same thing? Maybe we don't need to throw `FatalError` at all in these two cases if we're in pure scope and can instead apply some other logic.

**Comment by hermanventer** [comment]
It seems to me that the recovery code in CallExpression.js is too optimistic in this case. The concern in the Object.assign code is legitimate and just ignoring it does not seem safe. It seems possible to construct a test case that will do the wrong thing with the current implementation.

**Comment by sebmarkbage** [comment]
@hermanventer The CallExpression is pretty aggressive and fundamental to the approach of all the havocing. I don't know any issues with it at this point. Even aliasing isn't an issue because the havocing ensures that it isn't a concern:

We have to be careful with things like this:

```js
var obj1 = {x:0};
var obj2 = Object.assign(obj1);
obj2.x = 1;
return obj1.x;
```

The return value can't just be an abstract topVal, in this case. It must do something to ensure that obj1 might be obj2 (which it is). Havocing ensures that all of that works.
