### ISSUE TITLE
FuseBox plugin

### ISSUE THREAD

**Issue by MrFoxPro** [facebook/prepack#2085]
I saw that there are many plugins for this tool, but I would also like to see support for FuseBox. Are there any chances?

**Comment by gaearon** [comment]
We don't maintain any plugins ourselves. Prepack exposes a Node API so you can write a FuseBox (or any other tool) plugin for it. That said please also note Prepack is not ready for production use, and in general if you target web (and use, e.g., DOM APIs) you likely won't find it very useful right now.
