### ISSUE TITLE
Have a __invariant primitive

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2171]
Feature request: Add `global.__invariant(condition)`. 

It should simply emit a generator entry that conditionally throws an exception as a side effect when `condition` is `false`.

Unlike regular conditional-exception-throwing-code that Prepack could analyze alternatively, this would bypass any kind of state joining logic that blows up code generation.

**Comment by hermanventer** [comment]
How about just using __residual for this?

**Comment by NTillmann** [comment]
From a JavaScript perspective, `__residual` could do the job. But the generated code always involves another helper function, a bit too heavy-weight for my needs. I want something simpler (`if (...) throw new Error();`) that I can pattern-match on in the InstantRender compiler.
