### ISSUE TITLE
yarn install fails because of dependency upath@1.0.4 Node 10.x

### ISSUE THREAD

**Issue by LaRuaNa** [facebook/prepack#2181]
Getting following error while installing dependencies. Upath is a dependency of babe-core. So an update of babel-core solves the problem.
`error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".`

**Comment by gaearon** [comment]
What Node version are you using?

**Comment by LaRuaNa** [comment]
Currently v10.5.0
