### ISSUE TITLE
Update website to incorporate new logo

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2190]
See #2189 for assets.
And I guess the color scheme might have to change as well.

**Comment by Guru107** [comment]
@NTillmann Hi, 👋 Can I work on this? Don't have much OSS contributing experience. Looking forward to it. Let me know

**Comment by Guru107** [comment]
@NTillmann @hermanventer I came up with a color scheme, have a look. 
[Screenshot](https://raw.githubusercontent.com/Guru107/images/master/screen_shot.png)

**Comment by trueadm** [comment]
@Guru107 What about with the original logo, but the arrow being black rather than white?

**Comment by NTillmann** [comment]
Hm, I'd rather not change the logo appearance. But I agree with Dominic that that's a lot of green. Maybe just leave Prepack in white, both next to the logo, and in the big title?

**Comment by Guru107** [comment]
@trueadm I had removed the green background and made the arrow green.

**Comment by Guru107** [comment]
With white hero text and logo.

![ScreenShotWhite](https://raw.githubusercontent.com/Guru107/images/master/screen_shot_white.png)

**Comment by NTillmann** [comment]
I like it!
