### ISSUE TITLE
Bugs with throwing and Object.assign

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2241]
Test case:

```js
function foo(cond) {
  var d = {};

  if (cond) {
    throw new Error("I am an error!");
  }

  return d;
}

function fn(cond, cond2) {
  var a = {};
  var b = {
    prop1: 1,
    prop2: 2,
  };
  __makePartial(b);
  __makeSimple(b);
  var c = {
    prop3: 3,
    prop4: 4,
  };
  Object.assign(a, b, c);

  if (cond2) {
    var res = Object.assign(foo(cond), a); 
    return res.prop1;
  }

  return a.prop1;
}

__optimize(fn);
```

The output is wrong:
```js
  var _1 = function (cond, cond2) {
    if (cond2) {
      if (!cond) {}
    } else {}

    if (cond2) {
      if (cond) {
        var _4 = (__constructor.prototype = _$9, new __constructor());

        $$0.value = "Error\n    at foo (/Users/ADM/Projects/prepack/fb-www/input.js:5:11)\n    at fn (/Users/ADM/Projects/prepack/fb-www/input.js:26:29)", _$B(_4, "stack", $$0);
        $$0.value = "I am an error!", _$B(_4, "message", $$0);
        throw _4;
      } else {
        return void 0;  // <-- huh? how can it be undefined?
      }
    } else {}
  };
```

Object.assign makes the "to" object partial, but when we apply effects from a PossiblyNormalCompletion, the "to" object is no longer partial. When we try to access "prop1" on the object it thus returns `undefined`.

**Comment by hermanventer** [comment]
Here is a simpler repro, distilled from the one above:

```
let c1 = global.__abstract ? __abstract("boolean", "true") : true;
let c2 = global.__abstract ? __abstract("boolean", "false") : false;

function foo(cond) {
  if (cond) throw new Error("I am an error!");
}

if (c2) {
  foo(c1);
}

inspect = function() {
  return "success";
};
```

**Comment by hermanventer** [comment]
There is another problem with the original repro: When the return value from fn is combined with the PNC that contains the unhandled exception, it is not added back to all of the normal paths, but just one of them. Moreover, the return value is simplified with the path condition of the single path and hence the undefined value sneaks in. This is a specific instance of the general class of problems that I'm trying to resolve with a redesign of PNC. I may, however, be able to come up with a short term hack to make this specific kind of problem go away.
