### ISSUE TITLE
Invariant in `evaluateWithAbstractConditional`

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2277]
With the recent changes in https://github.com/facebook/prepack/pull/2274, we are now able to progress far further than before on our internal testing bundle when I add back in all the throw statements. However, we now run into a new `invariant`:

https://github.com/facebook/prepack/blob/master/src/realm.js#L1079

If I inspect the value of `completion`, it's a `PossiblyNormalCompletion` that is created on line https://github.com/facebook/prepack/blob/master/src/realm.js#L1053. I wonder why we have logic to handle `PossiblyNormalCompletion`s here https://github.com/facebook/prepack/blob/master/src/realm.js#L1064-L1071, but not for the other code path.

**Comment by hermanventer** [comment]
https://github.com/facebook/prepack/blob/master/src/realm.js#L1053 occurs when one (but not both) of the forked paths turns out to be infeasible. When that happens there is no fork and hence nothing to compose. Clearly, this explanation should appear in the code.

**Comment by trueadm** [comment]
So how can we not get this invariant? I'm not sure if you're proposing a solution or something else.

**Comment by hermanventer** [comment]
The links seem stale. Is there a test case that can reproduce the invariant?
