### ISSUE TITLE
Nested generators path conditions are not properly tracked

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2331]
See #2330 for desirable invariants and failing test cases.

This matters because simplifications (in abstract interpreter and serializer) happen based on path conditions.

**Comment by hermanventer** [comment]
#2330 is too simplistic, so that test cases that fail it are not useful. Is there another test case that fails even without #2330 ?

**Comment by NTillmann** [comment]
Only on giant internal bundles with nested optimized functions. 

It might still be worth manually inspecting the failing test cases. When I looked (before all the recent changes), I think it was pretty obvious that the path conditions didn't match up.

**Comment by NTillmann** [comment]
Doesn't repro.
