### ISSUE TITLE
Failing nested optimized function case #2

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#2359]
A really common failing nested optimized function case:

```js
function fn(x, obj, cond, abstractFunc) {
  var arr = Array.from(x);

  var a = {
    x: 5,
  };

  if (cond) {
    abstractFunc(function(y) {
      a = 1;
    });
  
    var z = a.x;

    var res = arr.map(function(item) {
      return z;
    });
  }

  return res;
}

__optimize(fn);
```

We hit an invariant with this particular case

**Comment by trueadm** [comment]
Without using the implicit nested optimized function logic:

```js
function fn(x, obj, cond, abstractFunc) {
  var arr = x;

  var a = {
    x: 5,
  };

  if (cond) {
    abstractFunc(function(y) {
      a = 1;
    });
  
    var z = a.x;

    var mapper = function(item) {
      return z;
    };
    __optimize(mapper);
    var res = arr.map(mapper);
  }

  return res;
}

__optimize(fn);
```

The error is different, it hits an invariant in `_getReferentializationScope` which I believe is the same error as https://github.com/facebook/prepack/issues/2335

**Comment by cblappert** [comment]
So far as I can tell, the second repro happens because we don't add leaked bindings to the optimized function's FunctionInstance, so state doesn't get cleaned up properly between passes of the serializer. Oddly enough, fixing that doesn't fix the first repro.

Looking into the first repro now.
