### ISSUE TITLE
Conditional optimized function simplification

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2375]
```js
(function () {
  function f(c) {
    if (c) {
      var foo = 42;
      __optimize(g);
      function g() { return foo; }
      return g;
    }
  }
  __optimize(f);
  global.f = f;
})();
```
prepacks to
```js
(function () {
  var _$0 = this;

  var _1 = function (c) {
    var _5 = function () {
      return c ? 42 : void 0;
    };

    return c ? _5 : void 0;
  };

  _$0.f = _1;
}).call(this);
```

Somehow, maybe via the path-sensitive treatment of conditionals in the visitor/serializer, we should be able to reduce `c ? 42 : void 0` to `42`.

**Comment by cblappert** [comment]
In this case, are you thinking of optimizing `g` as a callback or at the place of the `__optimize` call like functions nested in `map` calls? I think in the latter case, it makes sense to do this simplification. In the former case, we would want to distinguish when the function to optimize is declared in that conditional scope or not:

```
  function f(c) {
    if (c) {
      var foo = 42;
      __optimize(g);
      function g() { return foo; }
      return g;
    }
  }
  __optimize(f);
  global.f = f;
```
vs
```
  function f(c) {
    var foo = 42;
    function g() { return foo; }
    if (c) {
      __optimize(g);
    }
    return g;
  }
  __optimize(f);
  global.f = f;
```

In this second case, if we're treating g as a callback, we probably don't want to optimize `g` with the condition `c`, but I'm not sure how much that case matters in practice. Although, if we're optimizing things in pure mode, we can still optimize `g` in the context of `c` safely. 

Maybe we can always optimize with the `pathCondition` at the time of the `__optimize` call if the call is pure and only one `__optimize` call is made to the target function.

**Comment by NTillmann** [comment]
Already implemented.
