### ISSUE TITLE
CSE fails in an optimized function

### ISSUE THREAD

**Issue by sb98052** [facebook/prepack#2380]
Source:

```js
function f(n) {
  let x = n + 5;
  let y = n + 5;
  let z = n + 5;
  return [x,y,z];
}

__optimize(f);
```

Output:

```js
var f;
(function () {
  var _$3 = this;

  var _1 = function (n) {
    var _$0 = n + 5;
    var _$1 = n + 5;
    var _$2 = n + 5;

    return [_$0, _$1, _$2];
  };

  _$3.f = _1;
}).call(this);
```

Note that n+5 has not been identified as a common subexpression.

**Comment by trueadm** [comment]
This is because `x` `y` and `z` are all temporal entries in the case above, not a-temporal abstract values that go through the CSE system.

**Comment by NTillmann** [comment]
But what's the nature of the three serialized occurrences of `n + 5`?
Are those put into temporal binary generator entries because they might potentially call `.toString()`? And we want to allow that `.toString()` is not idempotent, or has some kind of internal side effect?

**Comment by sb98052** [comment]
Thanks. Digging in a bit, it seems that Nikolai is right. It guards against the possibility of overridden toString or valueOf calls. The line that causes the entries to turn into temporals is this: https://github.com/facebook/prepack/blame/c89f511102e3eb05ce17ad6788d6e442ad5cb9a7/src/evaluators/BinaryExpression.js#L95

It seems right (and nice).
