### ISSUE TITLE
wrong warning: side-effects from mutating the binding

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2393]
Prepacking this program...
```js
(function() {
  function fn(arg) {
    if (arg) return undefined;
    let f = 42;
    return f;
  }
  __optimize(fn);
})();
```
gives the following warning:
```
side-effects from mutating the binding "f" at location: 4:12 - 4:4
```
Why?

**Comment by trueadm** [comment]
Looks like an ES6 bug. Do we have a tag for ES6 features?

**Comment by NTillmann** [comment]
Yes, we do :-) Not sure if it's just ES6 related. The warning goes away when I remove the `if` statement.
