### ISSUE TITLE
This operation is not yet supported on document at documentElement

### ISSUE THREAD

**Issue by AleCaste** [facebook/prepack#2421]
When I run prepack I get an error on the following piece of code:
```
var document = __webpack_require__("./node_modules/babel-polyfill/node_modules/core-js/modules/_global.js").document;
module.exports = document && document.documentElement;
```
Can this be overcome somehow?

**Comment by trueadm** [comment]
@AleCaste You can attempt to fix this by adding abstract support for `documentElement` on `document`. See https://github.com/facebook/prepack/blob/master/src/intrinsics/dom/document.js.

**Comment by NTillmann** [comment]
Closing as it has been answered. Feel free to re-open if additional information is needed.
