### ISSUE TITLE
modified binding in nested optimized function wrongly eliminated

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2430]
This test fails.
```js
(function () {
    function mkLocation() {
        var x;
        function setter(y) { x = y; }
        function getter() { return x; }
        if (global.__optimize) __optimize(setter);
        return { setter, getter };
    }
    if (global.__optimize) __optimize(mkLocation);
    global.inspect = function() {
        var l = mkLocation();
        l.setter(42);
        return l.getter();
    }
})();
```
The prepacked code looks like this:
```js
(function () {
  var _$0 = this;

  var _2 = function () {
    var _4 = function (y) {
      return void 0; // <= no modified binding emitted???
    };

    var _5 = function () {
      return void 0;
    };

    var _3 = {
      setter: _4,
      getter: _5
    };
    return _3;
  };

  var _1 = function () {
    var l = _2();

    l.setter(42);
    return l.getter();
  };

  _$0.inspect = _1;
}).call(this);
```

Look at #2431 which marks two TODOs with #2430:
- first, a section of code in `_generatorOfEffects` that causes the modified binding to be eliminated entirely. The existing workaround with `environmentRecordIdAfterGlobalCode` was a hack that only worked for non-nested optimized functions.
- second, a second of code in `visitModifiedBinding` that associates a modified binding appearing in a nested optimized function with the global scope, which is not necessarily correct for nested optimized functions.

**Comment by cblappert** [comment]
Resolved by #2551
