### ISSUE TITLE
Use abstract value to havoc bindings

### ISSUE THREAD

**Issue by sb98052** [facebook/prepack#2446]
Havocing bindings currently sets their value to `undefined` which prevents us from distinguishing such bindings from uninitialized ones. We should instead use an abstract value. Perhaps we need a new abstract domain for locations.

**Comment by trueadm** [comment]
We could use an abstract value with a `kind` that is used to distinguish them. There'd be quite a few parts of the codebase that would need to be altered to understand this new `kind` though.
