### ISSUE TITLE
Reject aliasing in Array operators

### ISSUE THREAD

**Issue by sb98052** [facebook/prepack#2451]
It is desirable, in the case of nested Array operators, to not all-out leak. The contents of the array that are operated upon are leaked on creation. This leaves objects in the environment to deal with. The proposal here is to make all objects transitively reachable via reads to the bindings of optimized array ops "final" so that they are never used again. This solution is not general, but it is easier than the solution proposed in #2449.

The cases to reject include the ones caused by the `this` binding. 

```js
function f(c) {
    var arr = Array.from(c);
    
    let a = {foo:1};
	function op(o) {
		return a;
	}
    
    let mapped = arr.map(op);
    mapped[0].foo = 2;
    let x = a.foo;
    return x;
}

global.__optimize && __optimize(f);

inspect = () => {
  return f([{foo:42}]);
};
```

**Comment by trueadm** [comment]
Why do we want to reject the `this` binding? It's used all over our internal bundle for array methods :/

**Comment by sb98052** [comment]
Oh, I should have been more precise - we don't have to reject the `this` binding - just take it into account when rejecting aliasing effects. So if you use alias up `this` to the contents of the array or other non-local objects, then it leads to the same issues.
