### ISSUE TITLE
Incompatible with most recent node version?

### ISSUE THREAD

**Issue by kdex** [facebook/prepack#2520]
Installing prepack on a recent node version (I tried `v10.9.0` on a `4.18.5-arch1-1-ARCH` Linux machine) fails; downgrading my node is, in my case, not an option.

I'm hit with the same error that was brought to our attention by @rpkoller [back in June](https://github.com/facebook/prepack/issues/2135), and am afraid that `v8-profiler`, the dependency whose installation appears to be the cause of this issue, shows some maintenance issues.

They [don't support node > 7](https://github.com/node-inspector/v8-profiler/blob/master/.travis.yml#L18-L24) and seem to have had their last release over a year ago. Numerous issues were opened regarding this:

- https://github.com/node-inspector/v8-profiler/issues/126
- https://github.com/node-inspector/v8-profiler/issues/123
- https://github.com/node-inspector/v8-profiler/issues/120
- https://github.com/node-inspector/v8-profiler/issues/114
- https://github.com/node-inspector/v8-profiler/issues/104

but none of them have been addressed.

Is there anything you can do about this?

**Comment by hermanventer** [comment]
Is there another profiler with better support?

**Comment by kdex** [comment]
The v8 profiler in and of itself is fine; it's just the (seemingly unofficial?) node bindings that are causing these issues, i.e. the `v8-profiler` package.

> Is there another profiler with better support?

I would reckon so. I just stumbled upon [v8-profiler-node8](https://www.npmjs.com/package/v8-profiler-node8), which (despite of its name) claims to also support node 10.x.

I tried to install it on my machine, and it built just fine. Maybe you could experiment with substituting the node bindings and see if it also works with your test matrix?

**Comment by hermanventer** [comment]
Great to hear. If you would like to put a pull request to do the substitution I would be happy to test it locally.

**Comment by NTillmann** [comment]
Fix has landed.
