### ISSUE TITLE
Investigate ModifiedBindings issue on internal test case

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#2586]
Using a large internal test case, it is possible to get to a state where a ModifiedBinding has both its current and previous values undefined. This seems to happen in cases where optimized functions interact with Array nested optimized functions. It may have something to do with either effects not being applied/undone properly or choosing to optimize functions in the global scope.

See TODO added in #2551.

**Comment by matthargett** [comment]
#2595 was merged, so can this be closed now?
