### ISSUE TITLE
Mangle names like terser

### ISSUE THREAD

**Issue by fabiosantoscode** [facebook/prepack#2620]
Hey there!

This project seems to be an amazing tool, but the only thing that makes it short of a complete javascript minifier, is a mangler. Names should be 1 character long whenever possible. I suggest you implement the algorithm in uglifyJS and terser, which optimises for gzip-ability. If you'd like I can point you to where the code is.

I'm using prepack in my new project [jscomp](https://github.com/fabiosantoscode/jscomp), check it out!

**Comment by NTillmann** [comment]
Prepack is somehow orthogonal to what a typical minifier does; we think it would always make sense to just run a minifier after Prepack. In any case, if you put up a PR with a concrete proposal, we might accept that :-)
