### ISSUE TITLE
"total time has exceeded the timeout time: 1000"

### ISSUE THREAD

**Issue by dabugen** [facebook/prepack#2622]
Hello,

I was very eager to test your great tool, but it seems there is a timeout that you´ve set for the optimization to take place of 1000ms. However, my code is 34000 lines long (it´s a big web-app that does heavy calculations and so I was eager to see what Prepack might make out of it). With 1000ms, it stops at line 3XXX, so at least a timeout of 10000ms, better 15000ms would be needed to optimize my code. Is there a way you can possibly raise the timeout or make it user-selectable in the options?

Thanks so much and keep up the good work!

**Comment by hermanventer** [comment]
There is a such an option, see the --help of prepack_cli. How are you running the tool exactly?

**Comment by hermanventer** [comment]
We do run that website. I guess we just did not expect anyone to try such large programs with it. You should probably try to use the command line interface. See https://prepack.io/getting-started.html for instructions.

**Comment by dabugen** [comment]
Yes, I´d be absolutely eager to see what Prepack would do to such a complex program and how it can optimize it, to see how I can further optimize my code. It´s a program that is being run 24/7 with a steady 100% CPU load, so every optimization in terms of efficiency is very important to me. OK, I will try this way then. Thank you very much.
