### ISSUE TITLE
Is prepack development still active?

### ISSUE THREAD

**Issue by phpnode** [facebook/prepack#2628]
Hi, I noticed that prepack development has slowed, and was wondering if it's just paused or whether it's the end of the experiment and you're exploring other options?

**Comment by baptistemanson** [comment]
The readme has been updated to answer your question! https://github.com/facebook/prepack#status

**Comment by phpnode** [comment]
@baptistemanson thanks, somehow I missed that!

**Comment by natew** [comment]
I'd be really interested in a small explainer on the thinking behind giving up support, as there are many interesting possibilities why: level of difficulty, marginal improvements, other bigger improvements elsewhere, just lack of resources, or some combination.

I guess in my view, prepack seems so valuable, a big "game changer" for React. All the time I see code I've written as "easy for prepack to optimize" and in a similar vein to Prettier, it's kind of a magical ability: lets me write code naturally, and it handles optimization. React hooks also seems to tie in nicely with it, as it could reduce quite a bit of the memory/runtime burden of many hooks "out of the box".

Anyway, this isn't a prod, just genuinely curious.
