### ISSUE TITLE
Is it possible to convert recursive method to iterative?

### ISSUE THREAD

**Issue by Beraliv** [facebook/prepack#2633]
I have a code like:

```js
const getNumberOfParents = (element: HTMLElement) => {
  	return element.parentElement === null
	    ? 0
	  	: 1 + getNumberOfParents(element.parentElement);
}
```

I want to convert it to iterative automatically. Is it possible to do that with `prepack`?

I know it's the task for the engine like V8 but is it possible to speed up old browsers with it?

like:

```js
const getNumberOfParents = (element: HTMLElement) => {
	let currentElement = element;
	let count = 0;
	while (element.parentElement !== null) {
		count++;
		currentElement = currentElement.parentElement;
	}
	return count;
}
```

**Comment by NTillmann** [comment]
I don't think that Prepack would be the best tool for this task, as Prepack would have to be able to understand the meaning of the entire body,. even though the only thing that really matters is identifying the recursive structure.

**Comment by Beraliv** [comment]
Sad
Thank you anway
