### ISSUE TITLE
Wrong code generation for Top Level Variable Declarations

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#337]
Given a top level like:

```js
var x = 1;
x = 2;
```

Prepack turns it into:

```
var x = undefined;
var x = 1;
var x = 2;
```

I guess multiple "set" operations is correct but it is not correct to "set" it to `undefined` first. It would invoke a setter unnecessarily. It is also a bit unnecessary to print it as multiple `var` so it looks like an error.

**Comment by hermanventer** [comment]
With #897 the output now looks like this:

`var x;
(function () {
  var _$0_unique27277 = this;

  function _0_unique27277() {
    return _$0_unique27277.x;
  }

  x = 1;
  x = 2;
  inspect = _0_unique27277;
}).call(this);`

**Comment by NTillmann** [comment]
The latest code we generate for @sebmarkbage's original example is now:

```js
x = 1;
x = 2;
```

Which is wrong as the variable declaration has been eliminated.

**Comment by NTillmann** [comment]
The following serializer test currently fails:
```js
// does contain:var x                                                           
var x = 1;
```

This is what needs to be done:
- Add a file with this test code to test/serializer/basic, and 
- Fix the underlying issue (look in src/serializer/ResidualHeapSerializer.js at what happens with `ast_body` if not `this._shouldBeWrapped(body)`).

**Comment by NTillmann** [comment]
Remaining issue got addressed by referenced merged pull request.
