### ISSUE TITLE
Reduce number of cycles

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#360]
`flow check --profile` indicates that we have a giant cycle involving >211 files.
Flow conceptually concatenates all files involved in a cycle, which causes it to become slow when changing any file in the cycle.
We need to 1) drastically reduce the number of files involved large cycles, and 2) put a mechanism in place to prevent cycles from creeping in again.

**Comment by cblappert** [comment]
Addressed by #400 #409 #707
