### ISSUE TITLE
Implement Destructuring

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#415]
This isn't really more important than any other ES2015 feature other than that I had to work around this [specifically for Node](https://github.com/nodejs/node/blob/master/lib/buffer.js#L25-L26).

Seems like it should be easy. I might look into it if nobody else does.

**Comment by NTillmann** [comment]
Implemented by #697.

**Comment by sebmarkbage** [comment]
This is not quite done yet. E.g. the example `const { x } = { x: 5 };` from the PR doesn't actually work right now.

https://github.com/facebook/prepack/blob/8b5f40bcad73a3359b6388f784487d2c85f867ba/src/evaluators/VariableDeclaration.js#L39

https://github.com/facebook/prepack/blob/8b5f40bcad73a3359b6388f784487d2c85f867ba/src/partial-evaluators/AssignmentExpression.js#L101
