### ISSUE TITLE
Strict Mode Should Not Add Implicit Globals

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#454]
```js
(function() {
  "use strict";
  function a(x) {
    return x;
  }
  global.a = a;
})();
```
->
```js
(function () {
  "use strict";
  function _0(x) {
    return x;
  }
  a = _0;
}).call(this);
```

It's invalid in strict mode to add globals by assigning to an unknown variable. The serialization strategy for setting global properties is therefore invalid when the scope is strict.

**Comment by Wandalen** [comment]
As I reported in #823 , second pass for the same file throws "serializer failed" error.
