### ISSUE TITLE
Support serialization of DataView, ArrayBuffer

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#489]
Make serialization work for the related cluster of DataView, ArrayBuffer, and all typed arrays.
Add individual test cases for the different required aspects.

Look at #505 for an example of how to add serialization capabilities for typed arrays.

**Comment by dulinriley** [comment]
I just added the PR for sharing an ArrayBuffer among TypedArrays, I'll add in the DataView one soon as well.

**Comment by huhwhat777** [comment]
What should I do I'm llost

**Comment by dulinriley** [comment]
@sebmarkbage Let me know if there's anything you else you need from ArrayBuffer/TypedArray to get node.js working

**Comment by huhwhat777** [comment]
I don't know what I need a way to install what yall make I guess cause after yall make it I can't do nothing with it
