### ISSUE TITLE
"let" poops blank screen on "try it out"

### ISSUE THREAD

**Issue by sebringj** [facebook/prepack#515]
Go to "try it out", then try it out. You'll see.

**Comment by montogeek** [comment]
You mean this?
```js
(function() {
  let x = 0
  global.x = x;
})();
```

**Comment by sebringj** [comment]
let a = 'a';

**Comment by sebmarkbage** [comment]
That's because `let` doesn't create a property on the global object (unlike `var`). Therefore, that code is completely dead code and eliminated. The resulting file is empty.

**Comment by sebmarkbage** [comment]
We could maybe add a nicer message explaining this when we get an empty file.

**Comment by sebringj** [comment]
OK cool thanks for explaining.
I just tried this:
    let a = 1, b = 2; console.log(a + b)
then turned into this:
    console.log(3);
which is cool
