### ISSUE TITLE
Pipe into CLI

### ISSUE THREAD

**Issue by bevacqua** [facebook/prepack#517]
e.g `browserify main.js | prepack | uglify`

Expected: pull from standard input, push to standard output.

Actual:

```
Missing input file.
```

**Comment by InTheCloudDan** [comment]
Does anyone have a suggestion on how they would like this implemented? Pass it in as --pipe, or default the output to not have the surrounding text:

```
      console.log("+++++++++++++++++ Prepacked source code");
      console.log(code);
      console.log("=================");
```

**Comment by bevacqua** [comment]
+1 to not having surrounding text by default. imo, CLI should be:

```bash
prepack file.js
# print prepacked file as stdout

cat file.js | prepack
# print prepacked file as stdout
```

**Comment by InTheCloudDan** [comment]
@cblappert or @NTillmann any suggestion on how you would like it to be approached? I just don't want to submit something that's way off base.

**Comment by cblappert** [comment]
@sebmarkbage did a rewrite of the APIs before launch and might have an opinion on this. He's been trying to model the structure off of Babel.

**Comment by sebmarkbage** [comment]
I think the above proposal sounds good. Given that most people will want source maps I don't know how practical it is to just pipe but it does makes it easier to get started.

For large files I think we should just print them to stdout too. It's a little scary that it silently writes a file now.

Where should warnings go? Like the warning that a source map wasn't found? stderr I guess.

**Comment by bevacqua** [comment]
@sebmarkbage I think an API like this is acceptable if you want to throw in source maps:

```
cat file.js | prepack --source-map foo.js.map > foo.js
```

**Comment by gordomium** [comment]
This seems done. When should we release it?

**Comment by cblappert** [comment]
Sorry for the late response, the code for this is merged and should be included in the latest npm package.
