### ISSUE TITLE
Expose Node.js API interface for manipulating source code

### ISSUE THREAD

**Issue by gajus** [facebook/prepack#519]
I am implementing a webpack plugin, https://github.com/gajus/prepack-webpack-plugin.

The lowest level method in the Node.js API is `prepackFile`. As a result, I need to resort to using private methods (in the sense that they are not exposed) to implement the plugin.

It would be nice if prepack were to expose a lower level abstraction such as `prepackCode`.

**Comment by TheLarkInn** [comment]
That would be nice, @gajus you could also just execute this on a resulting bundle I believe. Am I mistaken @sebmarkbage @kittens?

**Comment by gajus** [comment]
> That would be nice, @gajus you could also just execute this on a resulting bundle I believe.

Thats what the plugin does (on the resulting chunk, to be specific).

**Comment by montogeek** [comment]
I just tried it in a React bundle, couldn't make it work: https://twitter.com/sebmarkbage/status/859842908194693121

**Comment by gajus** [comment]
> I just tried it in a React bundle, couldn't make it work: https://twitter.com/sebmarkbage/status/859842908194693121

Sorry, just published a fix.

**Comment by montogeek** [comment]
No, I mean, using `prepack` directly

**Comment by gajus** [comment]
> No, I mean, using prepack directly

Wrong issue thread in the case.

**Comment by montogeek** [comment]
No, I am talking about `prepack`, no your plugin.
Will try it later!

**Comment by sebmarkbage** [comment]
Prepack exposes the same APIs as Babel.

The "node" module exports everything from the "standalone" module.
https://github.com/facebook/prepack/blob/master/src/prepack-node.js#L20

This exposes a way to pass it code (or ast): https://github.com/facebook/prepack/blob/master/src/prepack-standalone.js#L31

The options object takes a filename.
