### ISSUE TITLE
Flow integration

### ISSUE THREAD

**Issue by phpnode** [facebook/prepack#523]
Hey, this is a great project! Do you currently have plans or a strategy for integrating this with Flow? I've written a babel plugin, [babel-plugin-flow-prepack](https://github.com/codemix/flow-runtime/tree/master/packages/babel-plugin-flow-prepack) which will convert flow type declarations into prepack models, it currently turns:

```js
  type Qux = {
    a: boolean
  };

  type Foo = {
    foo: string,
    bar: 123,
    qux: Qux
  };

  declare var obj: Foo;
```

into

```js
  const Qux = {
    a: __abstract("boolean")
  };

  const Foo = {
    foo: __abstract("string"),
    bar: __abstract("number"),
    qux: __abstract(Qux)
  };

  __assumeDataProperty(global, "obj", __abstract(Foo));
```

There are some things missing though, e.g. I'm not sure how to deal with arrays or functions, are there any plans to expand the types available?

**Comment by NTillmann** [comment]
Support for model arrays is still TBD.
For functions, the type (first __abstract argument) can be "function".

**Comment by phpnode** [comment]
@NTillmann thanks, also is there a way to indicate when we know the exact value of the declaration? e.g. I currently turn `a: 123` into `a: __abstract('number')`

**Comment by jaredly** [comment]
@phpnode I think that can just be `a: 123` -- it doesn't need to be abstract

**Comment by phpnode** [comment]
@jaredly awesome, now we just need arrays and unions :)

**Comment by vkurchatkin** [comment]
Is it me, or prepack doesn't do anything useful with abstract values at the moment?
