### ISSUE TITLE
Mistakenly deleted function

### ISSUE THREAD

**Issue by zsxsoft** [facebook/prepack#529]
Code:
```javascript
function getElementPosition (element) {
  let el = element
  for (var lx = 0, ly = 0; el !== null; lx += el.offsetLeft, ly += el.offsetTop, el = el.offsetParent);
  return {x: lx, y: ly}
}
const b = getElementPosition(document)
```

REPL Return:
```javascript
null or undefined
TypeError
    at getElementPosition (unknown)
    at repl:6:11
```

![image](https://cloud.githubusercontent.com/assets/2398785/25688069/677d51c0-30ae-11e7-8af5-9ccd1ab09956.png)

User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3080.6 Safari/537.36

I guess it may be the mistake of lexical processing in ``for`` statement....

**Comment by sebmarkbage** [comment]
This is because Prepack doesn't know about the environment variables like `document.offsetParent`. It thinks it is `undefined`. See the section on "Environment Matters". https://prepack.io/

Prepack doesn't yet support a full DOM environment.
