### ISSUE TITLE
Doesn't install in Yarn under Node 7.x

### ISSUE THREAD

**Issue by anmonteiro** [facebook/prepack#532]
The engines entry in `package.json` looks a little outdated, and doesn't install under Node.js 7.x:
https://github.com/facebook/prepack/blob/2f8de0085b2d6a562c8fc11c7ddea6dcbeadb605/package.json#L84

**Comment by anmonteiro** [comment]
Created #533 with a fix

**Comment by NTillmann** [comment]
This has been resolved by #509.
