### ISSUE TITLE
After transformation, some object attribute names written by keywords or reserved word  will go wrong in IE8

### ISSUE THREAD

**Issue by RubyLouvre** [facebook/prepack#535]
![image](https://cloud.githubusercontent.com/assets/190846/25688881/5357d9d4-30b5-11e7-9628-6757617c8d73.png)

**Comment by jdalton** [comment]
IE8 is as dead as this horse.

![](https://cloud.githubusercontent.com/assets/4303/25727378/c52fa582-30dd-11e7-91aa-a8af712a90a4.gif)

**Comment by NTillmann** [comment]
Closing due to lack of interest... If anyone would like to work on this, feel free to re-open.
