### ISSUE TITLE
Failed to optimize

### ISSUE THREAD

**Issue by nareshv** [facebook/prepack#537]
Using https://prepack.io/repl.html, Ran the code on https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.2/vue.js , threw this error

```
null or undefined
 TypeError at repl:541:23
 at repl:9:16
 at repl:6:2 ```

**Comment by deltaidea** [comment]
The culprit at 541:23 is this: `window.navigator.userAgent.toLowerCase()`
Prepack is still in development and [doesn't have knowledge about browser objects](https://github.com/facebook/prepack/issues/24). It doesn't know what's inside `navigator` or that it even exists.

**Comment by NTillmann** [comment]
Closing as question got answered.
