### ISSUE TITLE
Fails to optimize with "not an object" TypeError

### ISSUE THREAD

**Issue by naikus** [facebook/prepack#542]
Tried "prepacking" https://github.com/naikus/stage/blob/master/src/stage.js and got this error:
```
not an object
TypeError
    at repl:159:15
    at repl:155:13
    at repl:3:13
    at repl:2:1
```

**Comment by deltaidea** [comment]
Prepack is still in development and [doesn't have knowledge about DOM](https://github.com/facebook/prepack/issues/24). It doesn't know what's inside `document` and therefore doesn't know what to expect from `document.createElement("div")` which is on line 159 in your file.

I've tried adding DOM coverage myself using `__assumeDataProperty()` and `__abstract()` but no success. The only thing I can recommend is subscribe to #24 and wait.

**Comment by NTillmann** [comment]
Closing as the question got answered.
