### ISSUE TITLE
webpackJsonp is not defined | Angular + cli (webpack)

### ISSUE THREAD

**Issue by maxime1992** [facebook/prepack#544]
Trying to use `prepack` on an `Angular` project built with `@angular/cli` and I'm getting the following error : 

```
webpackJsonp is not defined
ReferenceError
```

In order to repro :

```
# install
yarn global add `@angular/cli`
ng new test-angular-with-prepack --skip-install
cd test-angular-with-prepack
yarn
# build : generate production build with source map
ng build --prod --sm
cd dist 
prepack main.*.bundle.js --out main.js
```

And the error happens here.

_If you don't want to install `@angular/cli` on your machine, here's a basic project : 
[test-angular-with-prepack.zip](https://github.com/facebook/prepack/files/975361/test-angular-with-prepack.zip) (unzip it, `yarn` and do what's after the comment `#build : generate production build with source map`)._

**Comment by deltaidea** [comment]
It's because `webpackJsonp` literally is not defined in the file. Prepack can't know what to expect from external global variables and if they will even exist at runtime. You must provide their definitions.

Add this at the beginning of the file:

```JavaScript
__assumeDataProperty(global, "webpackJsonp", __abstract("function"))
```

**Comment by TheLarkInn** [comment]
Oh is this all it would take to "pepper" the interpreter

**Comment by TheLarkInn** [comment]
I'm going to try and PR this on [prepack-webpack-plugin](github.com/gajus/prepack-webpack-plugin) today in the next 20min.

**Comment by NTillmann** [comment]
Closing as the question got answered.

**Comment by almcaffee** [comment]
I solved this issue by ensuring all other scripts are loaded before main.bundle.ts. Check your loader and console out the load order to ensure its correct.
