### ISSUE TITLE
Document programmatical usage

### ISSUE THREAD

**Issue by medikoo** [facebook/prepack#546]
Documentations elaborates on what results you can get from prepack, github documentations shows how it can be used from command line, but there seems to be no single word on how to use it programmatically, which makes a real blocker for many newcomers

```javascript
var prepack = require("prepack");

prepack(sourceCode); // ???
```

**Comment by deltaidea** [comment]
Click "Getting Started" in the header and you'll get to [prepack.io/getting-started.html](https://prepack.io/getting-started.html) where you can find this, and a list of options:

```JavaScript
import * as Prepack from 'prepack'

Prepack.prepack(codeString, options) // returns { code: string, map: SourceMap }
Prepack.prepackFromAst(babelAstNode, code, options) // returns { code: string, map: SourceMap }
Prepack.prepackFile(filename, options, callback) // callback(error, { code: string, map: SourceMap })
Prepack.prepackFileSync(filename, options) // returns { code: string, map: SourceMap }
```

**Comment by deltaidea** [comment]
Should probably duplicate the *"Getting Started | Try It Out"* buttons to the bottom of the page or even after each section.

**Comment by medikoo** [comment]
@deltaidea indeed, for some reason I assumed that "Getting Started" link at the top just scrolls to other content on main ("About") page. My bad.

Possibly placing link to "Getting Started" between "Examples" and "How does it work?" would help, it's the area where I was expecting some info on that.

Anyway I'm closing, sorry for noise.
