### ISSUE TITLE
unneeded throw for used variable

### ISSUE THREAD

**Issue by pvinis** [facebook/prepack#550]
why is this
```
(function() {
  let x = Date.now();
  let y = 3 + 4
  global.result = y;
})();
```
producing this
```
(function () {
  var _$0 = Date.now();

  if (typeof _$0 !== "number") {
    throw new Error("Prepack model invariant violation: " + _$0);
  }

  result = 7;
})();
```
?
should the date and error throwing be there, since x is not actually used?
is this a case of "if `Date.now()` is there, then the error throwing will be there. if your eslint or whatever tells you its not used, then you remove it, then the throw is not there."?

**Comment by cblappert** [comment]
Similar issue to #543 where we haven't worked on optimizing the output code much.

**Comment by jaredly** [comment]
title should be `for unused variable`

**Comment by NTillmann** [comment]
Closing as we are tracking the issue in #543.
