### ISSUE TITLE
Output generated has more characters than it 

### ISSUE THREAD

**Issue by jsaterfiel** [facebook/prepack#554]
`var config = {
getTeapot : function () {return 'hello I am a teapot';},
}`

becomes
`var config;
(function () {
  function _1() {
    return 'hello I am a teapot';
  }
  config = undefined;
  config = {
    getTeapot: _1
  };
})();`

Seems like the original code is actually more efficient?

**Comment by cblappert** [comment]
For simple examples with few levels of abstraction, Prepack may generate less efficient or larger code. Prepack provides the biggest advantage when there is a large amount of expensive computation or many layers of abstraction to remove.
