### ISSUE TITLE
Fix Scrollbar on prepack.io website

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#555]
Horizontal scrollbar on Prepack about page appears in the wrong place.

![image](https://cloud.githubusercontent.com/assets/3744743/25714480/fafcbca8-30ac-11e7-900a-87877868d37a.png)

**Comment by solodynamo** [comment]
Which browser you are using ? as it seems to be in correct place in mine.

**Comment by cblappert** [comment]
Update: misread the screenshot initially, its the example on the about page in Google Chrome.

**Comment by solodynamo** [comment]
Yeah it is ..got the issue and have solved, submitting a PR for it.

**Comment by TheSavior** [comment]
Should be resolved now. Thanks for reporting!
