### ISSUE TITLE
Published Rollup Plugin

### ISSUE THREAD

**Issue by tunnckoCore** [facebook/prepack#568]
https://www.npmjs.com/package/rollup-plugin-prepack

It seems that I can't install `prepack` in node > 7? I'm curious why is that limit `>=6.1.0 <7.0.0`?

But in any way, the plugin should work, i just don't have NVM currently, so i will write tests probably tomorrow and release v1.

edit: Probably worth set such integrations on separate section. I noticed that [plugin for webpack](https://www.npmjs.com/package/prepack-webpack-plugin) also was created in last hours and ranked at Github Trending.

**Comment by deltaidea** [comment]
See #509.
