### ISSUE TITLE
Test serialization of (Weak)(Map|Set) when entries have been deleted

### ISSUE THREAD

**Issue by hermanventer** [facebook/prepack#573]
More work is needed to deal with conditional additions and deletions. In particular $SetData, $MapData, $WeakSetData and $WeakMapData need to get tracked and need to support joins.

**Comment by NTillmann** [comment]
"$SetData, $MapData, $WeakSetData and $WeakMapData need to get tracked" So it's known to be broken when we enter partial evaluation mode? I am tagging this as a bug.

**Comment by yinghuitan** [comment]
@hermanventer, I am trying prepack against the following test:

```
(function() {
  let x = global.__abstract ? __abstract("boolean", "true") : true;
  let s = new WeakSet();
  if (x) {
   s.add(s);
  } else {
  }
  inspect = function() { return s.has(s); }
})();
```
Prepack fails at here:
https://github.com/facebook/prepack/blob/4824b47038131efcfd3e5f3928e2d2833a2aac23/src/intrinsics/ecma262/WeakSetPrototype.js#L56

Can you help me to understand what is the purpose of "ThrowIfInternalSlotNotWritable()" checking here? It is checking if the $WeakSetData internal field is a new created object during forked branch execution. I am not sure why this checking is necessary. For example, if I commented out this check, prepack just succeeds.

**Comment by hermanventer** [comment]
Since we are not tracking $WeakSetData, any code that writes to it during forked execution can cause wrong code to be generated and thus we guard against such writes and fail Prepack if they occur. If you comment this out, you should be able to write a test that where prepacked code produce a different result from the unprepacked code. Possibly we already have such a test. If not, now will be a great time to add it.

**Comment by yinghuitan** [comment]
@hermanventer, thanks. 
My understanding is that, I need to:
1. Add $WeakSetData to the "trackedProperties" array.
2. Make $WeakSetData to use ArrayValue reflection type so that any changes to it got tracked.
3. Modify any code that uses $WeakSetData as raw array to instead use the abstract operations operating on it.
4. Remove ThrowIfInternalSlotNotWritable().
5. Do similar steps for other fields, $SetData, $MapData, $WeakSetData and $WeakMapData.

**Comment by hermanventer** [comment]
This is not the only design that will work, but it seems doable.

**Comment by NTillmann** [comment]
Seems like it's all done.
