### ISSUE TITLE
Abstract Number with a Limited Value Range Fails Comparison

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#580]
https://github.com/sebmarkbage/prepack/commit/e5264b0a760c02db48c149b9cdae62c41526572a
```js
let c = 0;
let overflow = false;
function check() {
  return global.__abstract ? __abstract('boolean', 'true') : true;
}
function call() {
  if (check()) {
    c++;
    if (c > 2) {
      overflow = true;
    }
  }
}
call();
call();
inspect = function() {
  return overflow;
};
```

At the second call the value of `c` can become either `0 + 1` or `1 + 1` in the inner block. Neither of which is greater than `2`.

Found in lodash. https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L6691-L6718

**Comment by hermanventer** [comment]
I'm not sure we are ready to head down this slippery slope of reasoning over abstract arithmetic. This case, however, is not too hard. The standard approach is to add a Range domain to abstract values and use that to check simple relational constraints. I expect it will be one of the first steps down the slope for us.

**Comment by sebmarkbage** [comment]
This case doesn't need a Range domain necessarily. It is already a `ValuesDomain` of only two values. If it grows it might cause too many branches but for my particular use case it wouldn't.

So I just need to run the conditional over each value.

The thing that I don't fully understand yet is how things join.

If I add a third call then `overflow` should become abstract but in my case of two calls, it should be able to join and remain concrete.

**Comment by hermanventer** [comment]
Overflow will become abstract right away and making the condition "c > 2" concrete will not solve that problem.

**Comment by sebmarkbage** [comment]
It doesn't become abstract right now with one `call` because it never hits the line `overflow = true`. If the second call's condition `c > 2` is concrete, then it wouldn't hit the line `overflow = true` neither.

So what do you mean that it becomes abstract right away?

**Comment by sebmarkbage** [comment]
Oh you mean it the `check` branch becomes abstract and then it joins because overflow only has one possible value?

**Comment by NTillmann** [comment]
If you change "c++" to "c=c+1", your example works already! So supporting assignment operators like += abstractly seems to be the feature request here.

**Comment by sebmarkbage** [comment]
Interesting. I did try that in the bigger example and it didn't work but it must have been something else.

**Comment by NTillmann** [comment]
I opened an issue regarding the assignment operator: #594 594.

**Comment by sebmarkbage** [comment]
If I add a return value to the branches I get an invariant violation.

```js
(function(){
let c = 0;
let overflow = false;
function check() {
  return global.__abstract ? __abstract('boolean', 'true') : true;
}
function call() {
  if (check()) {
    c = c + 1;
    if (c > 2) {
      overflow = true;
      return 3;
    }
  }
  return 4;
}
a = call();
b = call();
inspect = function() {
  return overflow;
};
})();
```

```

Invariant Violation
    at invariant (lib/invariant.js:19:15)
    at Realm.get_captured_effects (lib/realm.js:374:31)
    at OrdinaryCallEvaluateBody (lib/methods/call.js:349:19)
    at InternalCall (lib/methods/function.js:974:49)
    at $Call (lib/methods/function.js:906:10)
    at FunctionValue.FunctionAllocate.F.$Call (lib/methods/function.js:1198:12)
    at Call (lib/methods/call.js:456:12)
    at EvaluateDirectCall (lib/methods/call.js:416:16)
    at exports.default (lib/evaluators/CallExpression.js:75:41)
    at LexicalEnvironment.evaluateAbstract (lib/environment.js:1232:16)
```

**Comment by NTillmann** [comment]
I filed an issue for the invariant failure (#596). As a workaround, things work if there's a common `return` statement at the end:

```js
(function(){
let c = 0;
let overflow = false;
function check() {
  return global.__abstract ? __abstract('boolean', 'true') : true;
}
function call() {
  let result = 4;
  if (check()) {
    c = c + 1;
    if (c > 2) {
      overflow = true;
      result = 3;
    }
  }
  return result;
}
a = call();
b = call();
inspect = function() {
  return overflow;
};
})();
```

**Comment by sebmarkbage** [comment]
Thanks! Working around these two issues seems sufficient to fix my use case.
