### ISSUE TITLE
Prepack generates illegal code for numeric property accesses

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#581]
Prepacking this
```
(function() {
  let obj = __abstract({}, "obj");
  __makeSimple(obj);
  x = obj[5];
})()
```
currently yields
```
(function () {
  var _0 = obj;
  var _$0 = _0.5;
  x = _$0;
})();
```

which is wrong, it should read `_0[5]` in there.

**Comment by NTillmann** [comment]
This is a small repro found by looking at the example in #577.

**Comment by sebmarkbage** [comment]
Ah. Interesting. I fixed the assignment case here: https://github.com/facebook/prepack/pull/564 but not the access.

**Comment by hermanventer** [comment]
I fixed all of them as part of a pull request that I've abandoned. I'll extract them from there and put up a separate request.
