### ISSUE TITLE
Serialize Object.preventExtensions() and maybe Object.freeze() as an optimization

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#585]
```js
let obj = {x:1};
Object.preventExtensions(obj);
inspect = function() {
  obj.y = 1;
  return obj.y;
}
```

This should yield `undefined` in a non-strict mode.

If all the properties are non-writable, non-configurable then we can optimize this by setting all the properties with setters and then calling `Object.freeze()` on the whole thing.

**Comment by NTillmann** [comment]
Addressed by #1436.
