### ISSUE TITLE
How to optimize this code by prepack??

### ISSUE THREAD

**Issue by tienn2t** [facebook/prepack#595]
i have a js code as 
`var a = [1,2,3,4,5,6];
for(var i=0;i<a.length;i++){
        console.log(a[i]);
}`

the result of prepack command
`No sourcemap found at hello.js.map.
+++++++++++++++++ Prepacked source code
i = undefined;
a = undefined;
a = [1, 2, 3, 4, 5, 56];
i = 0;
console.log(1);
i = 1;
console.log(2);
i = 2;
console.log(3);
i = 3;
console.log(4);
i = 4;
console.log(5);
i = 5;
console.log(56);
i = 6;
=================`

**Comment by lxzxl** [comment]
You need to wrap it in a IIFE.

```javascript
(function() {
  var a = [1,2,3,4,5,6]; for(var i=0;i<a.length;i++){ console.log(a[i]); }
})();

// result
console.log(1);
console.log(2);
console.log(3);
console.log(4);
console.log(5);
console.log(6);

**Comment by sebmarkbage** [comment]
Or use `let` instead of `var` since that doesn't set a global property.
