### ISSUE TITLE
Typed Arrays Don't Share ArrayBuffers

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#598]
This is a bug in #505 related to ArrayBuffers not being supported #489.

```js
let a = new Uint8Array(12);
let b = new Float32Array(a.buffer);

inspect = function() {
  a[0] = 123;
  return b[0];
}
```

This should share the same underlying `ArrayBuffer` but currently this gets serialized as two different typed arrays, which initializes with two different array buffers. Typed arrays are really just views on top of an `ArrayBuffer`. The `ArrayBuffer` is where the internal data is stored.

**Comment by sebmarkbage** [comment]
A related bug is that float arrays are not able to faithfully represent the precision of their underlying bits which is observable:

```js
let a = new Uint32Array(12);
let b = new Float32Array(a.buffer);
a[0] = 4294418165;
inspect = function() {
  let newA = new Uint32Array(b.buffer);
  return newA[0];
}
```

**Comment by Davidherrmann** [comment]
X
