### ISSUE TITLE
Add ability to choose from a set of examples on prepack.io/repl.html

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#603]
Currently, there's a single hard-coded example on that page.
It would be nice to have the ability to select from a set of (hard-coded) examples.
See https://www.typescriptlang.org/play/ for an example of what I mean. There's a "Select..." box.

The source code is in the gh-pages branch in the repl.html file.

The initial hard-coded examples can come from what's currently on the landing page, #473, and other cool snippets that you can think of.

**Comment by osterbergmarcus** [comment]
I would like to take a stab at this one

**Comment by osterbergmarcus** [comment]
With the new repl record feature do we still want to show a set of example code?
If so I'll have to update the current UI on my PR https://github.com/facebook/prepack/pull/638

**Comment by cblappert** [comment]
It would be nice to have the example code pre-recorded in the record dropdown so people can have a few already-done examples to switch through. If you could modify your PR to use the new record UI that would be great!

**Comment by osterbergmarcus** [comment]
Sounds good, I will look into it.

**Comment by NTillmann** [comment]
Implemented by #945.
