### ISSUE TITLE
Serialize IteratorPrototypes

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#608]
The iterator prototypes `IteratorPrototype`, `ArrayIteratorPrototype`, `MapIteratorPrototype`, `SetIteratorPrototype` and `StringIteratorPrototype` use intrinsic names that doesn't exist.

Here's a hack we could use:

```js
let ArrayIteratorPrototype = [][Symbol.iterator]().__proto__;
let MapIteratorPrototype = new Map()[Symbol.iterator]().__proto__;
let SetIteratorPrototype = new Set()[Symbol.iterator]().__proto__;
let StringIteratorPrototype = ""[Symbol.iterator]().__proto__;
let IteratorPrototype = [][Symbol.iterator]().__proto__.__proto__;
```

**Comment by NTillmann** [comment]
Related to #22, #26.

**Comment by sebmarkbage** [comment]
@NTillmann, what's left of #22? I haven't found anything lacking there anymore.

**Comment by sebmarkbage** [comment]
Test case:

```js
let ArrayIteratorPrototype = [][Symbol.iterator]().__proto__;
inspect = function() {
  return ArrayIteratorPrototype;
};
```

**Comment by NTillmann** [comment]
Hm, good question. Symbols in general seem to be actually working... Nice. But we have only a single trivial test case. So, let's forget #22 for this issue, and I'll add a comment to #22 that further tests are needed.

**Comment by pablo9503** [comment]
Un thanks for the help and i atorized YouTube cantidad put un their systematic a good verius   for them  so they cantnot heart More people
