### ISSUE TITLE
Serialization fail when used with webpack + react

### ISSUE THREAD

**Issue by seanpan** [facebook/prepack#611]
Serialization of an object of kind Map is not supported.
Serialization of an object of kind Set is not supported.

new Set() and new Map() both called in webpack bundle, prepack throw above messages and build fail.

#### index.jsx
```
import React, {Component} from "react";

class MyClass extends Component {
    render() {
        return (
            <div></div>
        )
    }
}

console.log(MyClass);
```

**Comment by deltaidea** [comment]
Related to #565 (merged 4 days ago).
Make sure you're on the latest `0.2.2-alpha.0` version (pushed 14 hours ago).

**Comment by seanpan** [comment]
Awesome! It works with 0.2.2-alpha.0 build. Although the output is really large (almost twice). It seems an extra optimization is necessary.
Thanks for your comment.
