### ISSUE TITLE
Scripts test-internal.js has an ambiguous line(inside search function), maybe?

### ISSUE THREAD

**Issue by abhisheksoni27** [facebook/prepack#612]
Could you please explain what this particular line is doing in the search function? [test-internal.js](https://github.com/facebook/prepack/blob/master/scripts/test-internal.js)

>if (fs.existsSync(dir))

```js
// Other code

function search(dir, relative) {
  let tests = [];

  if (fs.existsSync(dir)) 
/* This line. What is this doing? 
The body of the conditional is empty, so? */
  for (let name of fs.readdirSync(dir)) {
    let loc = path.join(dir, name);
    let stat = fs.statSync(loc);

    if (stat.isFile()) {
      tests.push({
        file: fs.readFileSync(loc, "utf8"),
        name: path.join(relative, name)
      });
    } else if (stat.isDirectory()) {
      tests = tests.concat(search(loc, path.join(relative, name)));
    }
  }

  return tests;
}

// Other code
```

**Comment by cblappert** [comment]
Since the if doesn't have brackets, its body is implicitly the next statement -- in this case the for loop. We should put curly braces around it so it's clearer.

**Comment by abhisheksoni27** [comment]
Oh, I see. I have read that in the literature, but yes, you are right. It's better to surround it with braces in cases where it might lead to confusion.

**Comment by cblappert** [comment]
Feel free to send a PR, I probably wont get around to it for a bit.

**Comment by abhisheksoni27** [comment]
All right. I'll send a PR right away.
