### ISSUE TITLE
Add lint check to gh-pages branch

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#618]
Figure out a way to add an eslint script to the gh-pages branch to enforce consistent coding style on webpage.

**Comment by archiekh** [comment]
Hi @cblappert,
Do you mean coding style of code examples on the webpage?

**Comment by cblappert** [comment]
My description was worded poorly. I would like to add a `npm run lint` command that runs eslint over the `js/` directory in the gh-pages branch in the same way that it runs over `.js` files in the master branch.

**Comment by archiekh** [comment]
Two more questions. After I add Prettier:
- Should I move additional libraries like `prism` and `prepack` to different folder, for example `lib`?
- Should I run `prettier` over the js/ to format a files in-place?

**Comment by archiekh** [comment]
https://github.com/facebook/prepack/pull/710

**Comment by cblappert** [comment]
Finished by above PR
