### ISSUE TITLE
How to deal with external dependencies??

### ISSUE THREAD

**Issue by deibeljc** [facebook/prepack#619]
Right now I have it so define (among other things) is already loaded into the browser env before my app gets loaded. When I try to run prepack it complains that

```
define is not defined
ReferenceError
    at core.js:6:1
```

I suspect it is because of the external dep thing I mentioned above, but perhaps it isn't

**Comment by NTillmann** [comment]
You need to tell Prepack about this assumption it can have about the initial environment, e.g. like  the following. Note that this is only safe to do if define cannot throw an exception, and doesn't update any observable state.

```js
(function() {
  __assumeDataProperty(global, "define", __abstract("function", "define"));
  define("a", 1, 2);
})();
```
