### ISSUE TITLE
Refinement of Abstract Branches

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#620]
We should be able to refine this to be only values in the domain `'A'` or `'B'` and therefore never hit the exceptional code path.

```js
(function() {
  let trueOrFalse = __abstract('boolean', 'true');
  function AorB() {
    return trueOrFalse ? 'A' : 'B';
  }
  let ab = AorB();
  if (ab === 'A') {
    result = 1;
  } else if (ab === 'B') {
    result = 2;
  } else {
    throw new Error();
  }
})();
```

Currently this has an error.

Specifically my use case is for `switch` statements which we don't seem to support on abstract values yet:

```js
(function() {
  let trueOrFalse = __abstract('boolean', 'true');
  function AorB() {
    return trueOrFalse ? 'A' : 'B';
  }
  let ab = AorB();
  switch (ab) {
    case 'A':
      result = 1;
      break;
    case 'B':
      result = 2;
      break;
    default:
      throw new Error();
  }
})();
```

**Comment by hermanventer** [comment]
We currently do no refinement anywhere and it will be a while before we get to it.

**Comment by NTillmann** [comment]
The first example works now. However, switch cases over abstract values don't seem supported yet.

**Comment by hermanventer** [comment]
Made issue #1378 for the switch statement part of this.
