### ISSUE TITLE
prepack es6 error

### ISSUE THREAD

**Issue by simon-yxl** [facebook/prepack#642]
'import' and 'export' may appear only with 'sourceType: module'

**Comment by Davidherrmann** [comment]
[Uploading  

>  #`@[xvideos.com_dba9baa14508262180d2542cba6f3d30.mp4…]()](url)`

 #M
![Uploading 1494851163672-1298890654.jpg…]()

**Comment by pablo9503** [comment]
Cantidad YouTube velo me fixit

**Comment by wdhorton** [comment]
I think this behavior is correct, right? Per the spec, you can only use 'import' and 'export' in modules.

**Comment by NTillmann** [comment]
As @wdhorton says, this is by design.
