### ISSUE TITLE
babel-types 6.x doesn't support `static` on ClassMethods

### ISSUE THREAD

**Issue by wdhorton** [facebook/prepack#661]
I'm working through the implementation of classes (#630), and I ran into an issue with the version of `babel-types` used in `prepack`. I should be able to implement `IsStatic` like this:
```js
export function IsStatic(classElement: BabelNodeClassMethod) : boolean {
  return classElement.static;
}
```
However, I get this flow error: property `static` Property not found in BabelNodeClassMethod.

It looks like the `static` property on BabelNodeClassMethod is only in version 7.x of `babel-types`, which is currently still in alpha.

What's the best way to resolve this?

**Comment by xtuc** [comment]
We can backport that change in Babel 6.

**Comment by wdhorton** [comment]
Ok! Should I go ahead and submit a PR for that to babel?

**Comment by NTillmann** [comment]
Is there a Babel PR to monitor for this issue?
As far as I understand, the remaining work here is to monitor when Babel supports this, and then update to the latest Babel, and find and remove this comment: `$FlowFixMe need to backport static property to BabelNodeClassMethod`

**Comment by NTillmann** [comment]
We've upgraded to Babel 7.
