### ISSUE TITLE
Empty output if use a global let

### ISSUE THREAD

**Issue by maxigimenez** [facebook/prepack#662]
Why the output is empty in this case?

#### Input
```JavaScript
let foo = "";
(function() {
  foo = "bar";
})();
```

#### Output (empty)
```
// Your code was all dead code and thus eliminated.
// Try storing a property on the global object.
```

**Comment by hermanventer** [comment]
foo has module scope. Only heap values reachable from the global scope are serialized. If you omit the let the above will have an output. You can also write "global.foo" to make things more obvious and less brittle.
