### ISSUE TITLE
Down-compiling forEach and map

### ISSUE THREAD

**Issue by anywhichway** [facebook/prepack#664]
Are you looking at down-compiling `forEach` and `map` beyond the example used on your home page? Using `forEach` and `map` when writing code is far less error prone and generally more readable than `for(<counter>;<limit>;<increment>)` or `for(...in..)` and `for(...of...)`. Also, the default programming style for `forEach` and `map` is to define the callback with lexical scope. This produces slower code. It seems like there should be many cases where static analysis could be used to down-compile `forEach` and `map` into appropriate `for` statements or at least lift the callback definition.

See http://www.jsbenchmarks.com/?anywhichway/loop/master/benchmark.js for some insight into performance differences.

I searched docs and issues for stuff related to the above, but I could not find anything beyond the abstraction tax elimination on the home page, which only partly addresses the above.

**Comment by hermanventer** [comment]
At the moment, Prepack operates by using an interpreter along with an Abstract Interpreter (AI) to run the global code, resulting in a mostly concrete heap with some abstract values here and there. The heap is then walked to produce a completely new, hopefully more efficient program that will recreate the heap when run against actual data.

The abstract values must be well behaved, which is to say that it must be known to the AI that the abstract values will not cause unknown changes to the heap or any abrupt changes in the control flow.

It is rather difficult to reduce loops with unknown bounds into a set of heap values that fit the above requirements.

An alternative approach, which I hope to start exploring this week, is to partially evaluate the given program, using the concrete and abstract values to simplify the original program by reducing expression with known values to constant expressions and by rewriting control flow to eliminate dead code. In the process it also becomes possible and desirable to do well known compiler optimizations such as function in-lining, loop unrolling, common sub expression elimination, strength reduction and so on. I expect that these optimizations will achieve what you are looking for.

It will be a while before V1 of that is finished and ready for production. I'm hoping for something by the end of the year, depending on how much time I can free up and how much help I get.

**Comment by anywhichway** [comment]
Thanks for the prompt reply. Close if you wish. Or leave open for others to see. I would assist, but the type of comp sci analysis of code required is beyond my capabilities.
