### ISSUE TITLE
Operation not yet supported on abstract values Date.now()

### ISSUE THREAD

**Issue by ncave** [facebook/prepack#682]
```
var d = new Date();
var isInvalidDate = isNaN(d); // ==> IntrospectionError at [Symbol.toPrimitive] (native)
var isInvalidDate = isNaN(d.getTime()); // ==> IntrospectionError at isNaN (native)
```
Is there a work-around? Thanks!

**Comment by NTillmann** [comment]
Right now, Prepack does not know that the number value associated with a Date is always non-NaN number. Plumbing that through will take some time.

You can either work around this by testing for whether you are running under Prepack (e.g. "!!global.__abstract", and not calling isNaN then), or testing whether "d instanceof Date", and then not calling isNaN.

**Comment by chirag04** [comment]
@NTillmann is there a better workaround that works with third party modules as well? Can we reopen this till then?
