### ISSUE TITLE
Investigate `metadata` argument

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#694]
`evaluators` in `realm.js` are defined as a function with 4 parameters, the last of which is optional `metadata`. This argument doesn't seem to be used anywhere.

1. Verify that this argument is not used anywhere.
2. Remove it.

**Comment by NTillmann** [comment]
I am pretty sure I've seen it being used. Look for example at SwitchStatement.js, the export default function.

**Comment by hermanventer** [comment]
The catch is that the places where it is used do not match the parameter name used in the signature, so just searching for occurrences "metadata" does not find any uses.

**Comment by NTillmann** [comment]
So it is used, case closed.
