### ISSUE TITLE
Improve Introspection errors reporting

### ISSUE THREAD

**Issue by hershi** [facebook/prepack#696]
When logging introspection errors, we don't provide much details today - a program location and a basic message. The user needs to figure out the real source of the issue, which can require a lot of work, especially for non-trivial code.
To be more specific, the errors are generally raised when we are trying to evaluate an expression that makes use of an abstract value where an abstract value is not supported. The error does not provide details about the source of the abstract value, which may require a lot of work on the part of the user. Example:
  * Assume a<sub>i</sub> are abstract values
  * Assume c<sub>i</sub> are concrete values
  * Consider the following code:
```
let c0, c1, c2;
c0 = c1 = c2 = 2;
let a0 = __abstract("number");

let x0 = a0+c0;
let x1 = c1 * c2 + c2 / c1;
let x2 = c1 ^ c2;
let x3 = x0 + x1 + x2 * c0;
let x4 = x3 * x2;
let a = new Array(x4);
```
Creating a new array with an abstract value for the length is not supported, and we will report the error:
```
This operation is not yet supported on abstract value
__IntrospectionError
    at Array (native)
    at no-filename-specified:10:9
```
But it's up to the user to figure out that x4 being abstract traces back to a0.

We should use the metadata stored in the AbstractValue objects to trace the abstract values back to their source (and augment that data as needed, if the current data is not enough for us to properly trace this back).

**Comment by NTillmann** [comment]
The abstract values carry in them the ability to produce ASTs, and those can be pretty printed. This could become part of the error message as well.
