### ISSUE TITLE
REPL broken?

### ISSUE THREAD

**Issue by FezVrasta** [facebook/prepack#701]
Whenever I try to use the REPL (both on Chrome and Firefox), I get no result and no errors. This happens with the default demo code:

```
(function() {
  function fib(x) {
    return x <= 1 ? x : fib(x - 1) + fib(x - 2);
  }

  let x = Date.now();
  if (x * 2 > 42) x = fib(10);
  global.result = x;
})();
```

Ideas?

**Comment by deltaidea** [comment]
In `repl-worker.js` there's an error on line 35:
```
Uncaught ReferenceError: originalError is not defined
```

This is likely a typo on line 5: `var originError = console.error;`
Should be `originalError`, not `originError`.

**Comment by hermanventer** [comment]
Wow. Fixed the typo in ff7610435fba1ad0856acfc96d5fa9d93c5378e4. We really should get Flow and Lint to run on these files.

**Comment by NTillmann** [comment]
Good catch Herman, but there was one more thing needed to revive the repl.html page: https://github.com/facebook/prepack/commit/60782797c0a0ce7a382816c62b3efa5fd65641ed I wonder if there might be other downstream users, e.g. the webpack integration, that got broken by the requirement for an "option" to be set.

**Comment by NTillmann** [comment]
Fixed by above commits.
