### ISSUE TITLE
prepack node v8.1.0

### ISSUE THREAD

**Issue by fengyun2** [facebook/prepack#720]
versions: node v8.1.0

error #prepack@0.2.3: The engine "node" is incompatible with this module. Expected version ">=6.1.0 <8.0.0".

**Comment by cblappert** [comment]
Trying it manually, Prepack seems to still work on node v8.1.0, so I'm removing the <8.0.0 restriction in #721

**Comment by NTillmann** [comment]
Fixed by referenced merged pull request.
