### ISSUE TITLE
Not very helpful error

### ISSUE THREAD

**Issue by vemacs** [facebook/prepack#750]
```
prepack base.js --compatibility browser --delayUnsupportedRequires --out base-processed.js
unknown reference type
```

There's no exception log, no trace, no anything.

**Comment by hermanventer** [comment]
Yes, pretty sad. Prepack encountered a case that supposedly should never happen. Which makes it hard for me to fix it without a way to reproduce it. Could you attach base.js, or some reduced version of it that you are OK with sharing?

**Comment by vemacs** [comment]
@hermanventer Here's a ZIP with the compiled script and the source map: https://transfer.sh/ZRytf/dist.zip
