### ISSUE TITLE
Array length doesn't need to be cached anymore

### ISSUE THREAD

**Issue by infusion** [facebook/prepack#774]
Hi,

```
for (var i = 1, len = points.length; i < len; i++) {
```

is kept as is by prepack. If len or array length isn't changed otherwise, it's totally fine to reduce to

```
for (var i = 1; i < points.length; i++) {
```

Since modern JS engines optimize this anyway.

**Comment by hermanventer** [comment]
Prepack currently optimizes only the initialization phase. Any loop encountered during initialization will get unrolled (if the loops bounds are not known Prepack will just give up and fail to optimize).

Eventually, Prepack will attempt optimization of non-initialization code and will have to deal with loops that cannot (or should not) be unrolled. When that happens, many local variables will go away and constant expressions will get folded into constants.

Also note that in your example, it is not safe to assume that points.length will never change from one iteration to the next.

**Comment by NTillmann** [comment]
This seems to be resolved, as this is currently by design.
