### ISSUE TITLE
Run prettier as part of eslint

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#792]
Prettier is a great formatter, but it doesn't currently surface any formatting discrepancies in Nuclide. Look into `eslint-plugin-prettier` to get formatting information with linting information.

Also investigate whether prettier automatically fixes all lint errors and if eslint is still necessary.

**Comment by NTillmann** [comment]
> Also investigate whether prettier automatically fixes all lint errors and if eslint is still necessary.

`eslint` is doing much more than just checking for formatting rules. For example, it disallows the use of `eval`, switch-case-fallthroughs, octal literals, `with`, unused variables, ...

**Comment by NTillmann** [comment]
So the remaining question is basically if there's a convenient way of running Prettier in Nuclide, or detecting that Prettier needs to get run.

**Comment by yinghuitan** [comment]
Actually, Prettier is already integrated into Nuclide. You will need to add "@format" at the top of the file header to opt-in the auto-formatting and linter UI.

**Comment by NTillmann** [comment]
@yinghuitan, So we should add @Format to every single file? Any way to configure that more centrally?

**Comment by yinghuitan** [comment]
@NTillmann, if we want to enable Prettier for all prepack codebase, we can just use ESLint plugin: https://github.com/prettier/prettier#eslint
To surface ESLint warnings in Nuclide diagnostics UI, we need to manually install linter-eslint Atom package:
https://github.com/AtomLinter/linter-eslint
We can use "cmd-shift-C" to format code in editor, see the format warning in Nuclide UI, and select the "auto-fix" tooltip button to fix the format issue. 
@cblappert, do you want me to take over this?
