### ISSUE TITLE
Adapt module-handling code to recent Metro packager changes

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#798]
Instead of
```js
__d(function(...) { ... require(42) ... require(23) ... }, 1);
```
the Metro bundler will have another mode that will emit code of the form
```js
__d(function(...) { ... require (1) ... require(0), 1, [23, 42]);
```

Our code in `modules.js` needs to be able to handle either version.

**Comment by davidaurelio** [comment]
The

**Comment by NTillmann** [comment]
See https://github.com/facebook/metro-bundler/commit/dee58678c627e97024000c9b82e372dbd7ba3bf0 for the relevant Metro changes.

**Comment by davidaurelio** [comment]
The new mode produces code as follows:

```js
__d(function(global, require, module, exports, dependencyMap) { 
  ... 
  require(dependencyMap[1] 
  ... 
  require(dependencyMap[0]_; 
  ... }, 1, [23 42]);
```

**Comment by NTillmann** [comment]
All of the work required to deal with this in Prepack has landed.
