### ISSUE TITLE
Besides global code, support prepacking additional independent functions

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#799]
Consider global code like this:
```js
initStuff()
initMoreStuffA()
initMoreStuffB()
```

Assume that `initMoreStuffA()` and `initMoreStuffB` have the following properties:
1. they do rely on the effects of `initStuff`
2. they do not effect each other, e.g. `initMoreStuffA` does not read or write any heap location that `initMoreStuffB` writes to, and the other way around.

It seems that we should be able to detect the 2. property.

Now assume that the global code changes, so that `initMoreStuffA` and `initMoreStuffB` don't actually run as part of the global code, but get invoked conditionally. We should be able to prepack the two functions separately, and serialize code for them that patches the heap appropriately.

**Comment by javache** [comment]
This looks great. For our use-case specifically, A and B will be independent but may be writing to shared parts of the heap.

```
functon initStuff() {
  global.registry = {};
}
function initMoreStuffA() {
  global.registry['A'] = 'a';
}
function initMoreStuffB() {
  global.registry['B'] = 'b';
}
```

Another property that would hold true for this is that.

```
initStuff()
initMoreStuffB()
initMoreStuffA()
```

will result in the same heap layout as the original.

**Comment by hermanventer** [comment]
I'll take on the bits needed for checking that initMoreStuffA and initMoreStuffB are independent from each other.

**Comment by NTillmann** [comment]
Decomposing the overall required work:
0. Add option to Prepack to identify a set of function on the global object which should get handled, and then exploring them separately for effects after the global code is done.
1. Build a checker to determine that effects are mutually disjoint (Herman volunteered for that).
2a. Enhance serializer to rewrite those functions for the special case that they are pure, i.e. do not mutate any shared state.
2b. Enhance serializer to rewrite those functions in the general case, taking care of general effects, including mutations of shared state.

2a by itself seems to be a very useful feature, and should be strictly easier than 2b.

**Comment by NTillmann** [comment]
1+2+3 are done, 4 is still missing.

**Comment by NTillmann** [comment]
#988, #989, #990 are done.
Still open is #987.
Recently new issues surfaced and are still open: #1250 and #1238 and #1140.

**Comment by NTillmann** [comment]
#988, #989, #990, #1238  are done.
Still open are #987, #1250, #1140, #1093.
New feature requests:
- Support multiple additional functions updating a binding (#1087)
- Support for nested additional functions (#1398)

**Comment by NTillmann** [comment]
#988, #989, #990, #1140, #1238, #1093  are done.

Bugs still open are:
- Incorrect sharing of bindings of residual/additional functions (#1250)

New feature requests:
- Make Additional Functions work with arguments (#987) --- first basic version is working!
- Support multiple additional functions updating a binding (#1087)
- Support for nested additional functions (#1398)

**Comment by cblappert** [comment]
I think the goals specified in this PR are mostly achieved. Additionally, this specific use case is no longer needed, so I'm closing this task.
