### ISSUE TITLE
Harmonize Prepack CLI with internal options

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#804]
The Prepack CLI (`prepack-cli.js`) exposes a certain set of options. However, internally, Prepack currently has a richer option set (`options.js`).

We need to...
- be able to encode all options via the CLI,
- when Prepack is invoked directly, not via the CLI, be able to output the corresponding command-line to simplify error reporting and debugging.

To enforce the equivalence of our command-line and the internal options, there should be an invariant for every prepack invocation: take the options, turn them into a command-line, re-parse the command-line to get reparsed options --- then the original options and the re-parsed options should be structurally equal.

**Comment by sebmarkbage** [comment]
I don't think all options should necessarily be required to have a CLI equivalent. E.g. callbacks for piecemeal error handling wouldn't be. Another could be passing AST forms or in-memory representation of source maps. The point of a programmatic API in the same language is that it can share richer data structures than the CLI. However, everything that can be translated should have an equivalent as much as possible.
