### ISSUE TITLE
Unboxed context value is passed to function call

### ISSUE THREAD

**Issue by yinghuitan** [facebook/prepack#821]
The following test should 
```js
Object.prototype.f = function() {
  assert.sameValue(typeof this, "object", "Context object should be boxed.");
}
var n = 42;
n.f();
```
In the code, primitive value n will be boxed into object for method lookup. But Prepack seems to pass the original unboxed primitive value n as context to function f. I think the boxed object should be passed instead.

**Comment by cblappert** [comment]
If you remove the `"use strict"` emitted at the top of the program output by prepack the first time, prepacking it a second time will succeed. The error is because prepack tries to implicitly define a global in strict mode.

This is a known issue, see #454

**Comment by NTillmann** [comment]
Cannot reproduce. This serializer test case passes:

```
(function() {
  Object.prototype.f = function() {
    return typeof this;
  }
  let n = 42;
  let t = n.f();
  inspect = function f() { return t; }
})();
```

**Comment by yinghuitan** [comment]
You are right. We are correctly here in behavior:
1. In strict mode, we are passing the unboxed primitive value. 
2. In non-strict mode, we are passing the boxed value wrapping the primitive.
3. However, if the target function is NativeFunctionValue(like toString()), we are skipping the boxing even under non-strict mode, and pass non-box primitive value.
