### ISSUE TITLE
Serializer failed

### ISSUE THREAD

**Issue by Wandalen** [facebook/prepack#823]
Kind of ticket : issue
Version : prepack@0.2.5
Options : none

Hello. I got "serializer failed" after attempt to run prepack second time with this file :
https://github.com/Wandalen/wTools/blob/master/staging/abase/akernel/aKernel.s
Any idea how to avoid that error?

**Comment by cblappert** [comment]
If you remove the "use strict" emitted at the top of the program output by prepack the first time, prepacking it a second time will succeed. The error is because prepack tries to implicitly define a global in strict mode.

For more information, see #454

**Comment by Wandalen** [comment]
Is not that bug? For me strange that second execution causes problems.
If prepack map program from language A to language A, it also should be able to take its output as input. Am I wrong?

**Comment by NTillmann** [comment]
It's a bug, tracked in #454, and should get fixed indeed.

**Comment by Wandalen** [comment]
I see. Thanks for explanation.

**Comment by NTillmann** [comment]
Closing this issue as it's a duplicate.
