### ISSUE TITLE
Clean up Options.

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#841]
Look at options.js. There are a few things that should get cleaned up:

1. `Options` should really be just the union type of `RealmOptions` and `SerializerOptions`. Why is there the silly name-difference between `errorHandler` and `onError`?
2. The `Options` data type (and associated helper functions) should not be defined in options.js, move them to a file called `prepack-options.js`, which is not referenced by the prepack core engine. This is currently violated by src/environment.js in the `executePartialEvaluator` function. It should probably take a new `PartialEvaluatorOptions` types, which only contains `sourceMaps`.

**Comment by echo304** [comment]
I'm gonna tackle this issue ✋

**Comment by NTillmann** [comment]
Fixed by merged pull request.
