### ISSUE TITLE
#842 Turned delaying of values off, but delayedValues in statistics is nonzero

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#844]
Investigate why this statistic is nonzero even when delaying values is turned off.

**Comment by hermanventer** [comment]
Might be glitch in the dashboard. The values are currently at zero.

**Comment by NTillmann** [comment]
Reassigning to @cblappert, happy to look at it with a repro...

**Comment by cblappert** [comment]
Looks like it was just something transient in the dashboard, closing.
