### ISSUE TITLE
Consider Making "Is" Brand Checks Extensible or Hard Code Known Ones

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#876]
Babylon has a lot of experimental features and proposals that have not yet landed in the standard yet. They're used to get usage and evaluate new proposals before they land in the standard.

Others, like JSX, don't have a single fixed semantic. They are used slightly differently depending on framework. It's not always desirable to lower the representation since it's not fully implementable in terms of known features and sometimes it is important to preserve the high level representation. E.g. for debuggability.

I've written a JSX evaluator for React which I just plug in to `realm.evaluators`.

This works pretty great. Except there are a few brand checks that are hard coded lists. Unknown extensions throw. Specifically these: https://github.com/facebook/prepack/blob/fbae09bb75ba25594cf1397562e38dda5194f96c/src/methods/is.js#L217-L287

I see a few ways around it:

1) Make this check extensible. E.g. through a mechanism on realm just like evaluators.

2) Hard code known syntactic extensions. They're already hardcoded into Babylon since it's tough to build a fully extensible parser for JS. So the rule could be that we accept a hardcoded extension at the same time they're accepted to Babylon.

3) Make the catch-all return a reasonable default value for these instead of throwing. That would cover almost all extensions.

Thoughts?

**Comment by hermanventer** [comment]
At the moment we essentially assert that unknown extensions will never come our way. Better would be to generate a compiler diagnostic indicating the source location.

Eventually, it probably makes sense to handle everything that Babylon can give us, but I don't think that is going to happen anytime soon.

When you do add support for a new feature, such as JSX, then change what needs to change.

**Comment by sebmarkbage** [comment]
Ok sent a PR for this one case. #877
