### ISSUE TITLE
AbstractObjectValue with an object template as its value domain is a dubious thing

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#882]
It should probably be disallowed, which will have consequences for...
- how `JSON.parse`/`JSON.stringify` are implemented
- how we create `__abstract` object values

The current design is dubious as...
- the single value domain implies that the abstract object value in fact has a precise identity, and
- the current implementation somehow leaks those template objects, but only after it gave them an intrinsic name (in `rebuildNestedProperties`), which is dubious as intrinsic values should exist ahead of time, but these abstract values are only created at particular points in time, possibly in nested generators

I imagine that the solution to this problem involves...
- deprecating (or removing) the idea of template objects, and dealing with the consequences in the implementation of `__abstract` and the `JSON` code.
- introducing a new primitive like `__makeIntrinsic(object, name)` which makes an object intrinsic with a particular name, possibly tied to the currently active generator. This can then be combined with `makePartial` or `makeSimple`.

Search the code for `TODO #882` references.

**Comment by hermanventer** [comment]
This issue is quite stale now and is unlikely to get addressed any time soon, if ever.
