### ISSUE TITLE
Generate better code in the presence of `this` and `arguments` in nested residual functions

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#886]
Currently, if we determine that a residual functions contains references to `this` or `arguments`, it triggers some of de-optimizations. However, we should really only look at outer residual functions to determine this, but we currently look at nested functions within outer residual functions to set the `usesArguments` and `usesThis` flags.

Look at the `ClosureRefVisitor` to find the code that sets the `usesArguments` and `usesThis` flags.
Write test cases that trigger this and the resulting de-optimization (look for code that uses `usesArguments` and `usesThis`) for nested functions, and see how the generated code will get better once the detection works right.

**Comment by NTillmann** [comment]
Here's a test case that shouldn't fail:

```js
// does not contain:call
(function() {
    var f = function() {
        return function() {
            return (function() { return this.x; }).bind({x: 42});
        }
    }
    var g1 = f();
    var g2 = f();
    var g3 = f();
    inspect = function() { return g1() + g2() + g3(); }
})();
```

**Comment by a8m** [comment]
Closing in favor of #1621
