### ISSUE TITLE
`yarn prepack -- --help` doesn't terminate

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#889]
It prints the help text, as desired, but then it stays in prepacking mode instead of terminating.

**Comment by echo304** [comment]
Let me tackle this issue ✋

**Comment by echo304** [comment]
From the perspective of product design,
does it need to terminate process when `--help` option is passed even if other arguments(ex-filename) are passed too? 
If so, this issue can be fixed by adding one line of code that terminate process when `arg === 'help'`.
Any thought?

**Comment by NTillmann** [comment]
Good question. Most tools I know typically terminate after printing the help text when asked to do some via --help. You might complain if there are any more arguments present, but I don't think it's necessary.

**Comment by NTillmann** [comment]
Fixed by merged pull request.
