### ISSUE TITLE
Serializer bug: Function scopes

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#892]
The ResidualHeapVisitor puts any `FunctionValue` into the `realmGenerator` scope, representing the top-level scope. This corresponds to the way we serialize functions: The code in ResidualFunctions/`spliceFunctions` tries to put all function declarations at the top level.

However, this is wrong in general.
The following test case demonstrates that it's important that Functions are associated with the right scope, and not just getting treated as always being at the top-level scope:

```js
(function() {
    let x = global.__abstract ? __abstract("boolean", "(true)") : true;
    if (x) {
        let obj = { time: Date.now() };
        f = function() { return obj; }
    } else {
        let obj = { time: 99 };
        f = function() { return obj; }
    }
    inspect = function() { return f().time > 0; };
})();
```

**Comment by yinghuitan** [comment]
Take this one to get more familiar with residual function serialization.
