### ISSUE TITLE
Serialization of functions might not configure strictness right

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#893]
In ResidualFunctions, `unstrictFunctionBodies` and `strictFunctionBodies` are properly set --- but only for the simple case! For the second case, where a `factoryNode` is created to avoid code duplication, strictness is ignored.

Test cases should be created to bring out the issue, and then it needs to get fixed.

**Comment by NTillmann** [comment]
Here's a test case for the simple case that already works. Please just add this test case to `test/serializer/basic` for completeness.
```js
(function() {
    var isStrict = function() {
        "use strict";
        return !!this;
    };
    inspect = function() { return isStrict(); }
})();
```

And here's a test case that doesn't work, and that's what need to get fixed:
```js
(function() {
    var isStrict = function() {
        "use strict";
        return function() {
            // This function is too big to be inlined.
            return !!this;
        }
    };
    let f1 = isStrict();
    let f2 = isStrict();
    let f3 = isStrict();
    inspect = function() { return f1() && f2() && f3(); }
})();
```

**Comment by yinghuitan** [comment]
This issue has been fixed.
