### ISSUE TITLE
Fix Location reporting in repl

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#920]
Before in the website, errors would output line and column numbers and turn this into a clickable link that would highlight the line in the code. 

Error locations now no longer seem to be displayed at all after updating the repl to prepack v0.2.6. Restore the original functionality.

**Comment by NTillmann** [comment]
@hermanventer, might this be related to #900 / #916? The invariant violation there has the same error message that's now presented to me on the website when I type in code with a syntax error: 
```
There's no running execution context
```

**Comment by hermanventer** [comment]
These are for introspection errors.

**Comment by NTillmann** [comment]
I see, wasn't clear to me from the description that this issue is meant to only apply to introspection errors...

So the canonical example for which we'd like to get a clickable error position is
```
(function() {
  let a = __abstract();
  a + 5;
})();
```

I'll open another issue just for the syntax error problem.
