### ISSUE TITLE
Object Rest and Spread Support

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#927]
_This is something that comes up from optimizing residual functions more than the initial path._

Let's talk about object rest and spread support. [This](https://github.com/tc39/proposal-object-rest-spread) is soon going to land into the spec. This is a pretty common pattern in React and similar functional style updates. It is a loop but it's much simpler than arbitrary loops.

This is typically down compiled to `Object.assign` but the actual semantics are slightly different and simpler.

```js
var a = __abstract('object', 'a');
__makeSimple(a);
var b = {...a, x: 1};
result = b;
```

I would expect this to be able to  compile down to:

```js
result = {...a, x: 1};
```

I figured this would be model as the newly created object after the spread would be partial and simple. This object is now known to be simple because all the newly created properties that we don't know about have to be simple.

The more general form of this is implementing abstract values in `Object.assign`.

E.g.
```js
var a = __abstract('object', 'a');
__makeSimple(a);
var b = Object.assign({}, a, {x: 1});
result = b;
```

However this is not quite the same, because this will invoke setters on the newly created object which in theory could be unsafe for arbitrary objects. It would require the first object to be "simple" as well. I suppose we could validate that the first object is not abstract and doesn't have any setters. Therefore the call is safe regardless what unknown properties we would be reading.

Ideally, rest should be able to work but it's a bit harder to serialize.

```js
var a = __abstract('object', 'a');
__makeSimple(a);
var {x, ...b} = a;
result = b;
```

Which should compile down to:

```js
var {x, ...$0} = a;
result = $0;
```
or maybe:
```js
var $0 = {...a};
delete $0.x;
result = $0;
```

**Comment by NTillmann** [comment]
Both rest and spread operators could be made to work for such simple cases, basically creating abstract values for which we know how to generate code that does the right thing. 

What will require some thought is how to support further property access operations on the resulting objects: how does it relate to partial / simple objects, which properties are known to exist...
