### ISSUE TITLE
Generator sometimes did not emit Object.defineProperty() correctly

### ISSUE THREAD

**Issue by yinghuitan** [facebook/prepack#930]
If some code `Object.defineProperty()` for non-default property attributes, then `Object.defineProperty()` for default property attributes, generator will not emit two `Object.defineProperty()` call but one default assignment(because of seeing the second `Object.defineProperty()` with default property attributes) which is wrong because assignment will not change property descriptor attributes.

The following testcase demonstrates this:
```js
(function() {
    global.obj = 13;
    Object.defineProperty(global, "obj", { enumerable: false, configurable: true, writable: true, value: 42 });
    Object.defineProperty(global, "obj", { enumerable: true, configurable: true, writable: true, value: 23 });
    inspect = function() { return JSON.stringify(Object.getOwnPropertyDescriptor(global, "obj")); }
})();
```

**Comment by NTillmann** [comment]
The bug is in how src/methods/properties.js/`InternalUpdatedProperty` and src/utils/generator.js/`emitDefineProperty` interact.

The pull request that fixes the issue should include the above test case as a new file in the test/serializer/basic directory.

**Comment by NTillmann** [comment]
Fixed by referenced merged pull request.
