### ISSUE TITLE
Improve captured closure binding initial value serialization

### ISSUE THREAD

**Issue by yinghuitan** [facebook/prepack#935]
For 
```js
(function() {
  let x = 13;
  let f = function() { return x += 3; };
  let g = function() { return x -= 2; }
  inspect = function() { return f() + g(); };
})();
```

We generates:
```js
(function () {
  var __scope_0 = Array(1);

  var _1 = function () {
    var __scope_1 = 0;
    var __captured__scope_1 = __scope_0[__scope_1];
    if (!__captured__scope_1) __scope_0[__scope_1] = __captured__scope_1 = {
      x: 13
    };
    return __captured__scope_1.x += 3;
  };

  var _2 = function () {
    var __scope_1 = 0;
    var __captured__scope_1 = __scope_0[__scope_1];
    if (!__captured__scope_1) __scope_0[__scope_1] = __captured__scope_1 = {
      x: 13
    };
    return __captured__scope_1.x -= 2;
  };

  var _0 = function () {
    return _1() + _2();
  };

  inspect = _0;
})();
```

You can see the same initialization value "{x: 13}" is duplicately serialized in every accessed residual function which increases code size.

I think we should generate one copy.

**Comment by NTillmann** [comment]
I agree that this is inefficient. But I don't see a simple works-for-all fix.
Good heuristics might help.
It used to be the case that there were no such lazy objects, instead, we generated the following code:
```js
(function () {
  var __captured_x = 13;

  var _1 = function () {
    return __captured_x += 3;
  };

  var _2 = function () {
    return __captured_x -= 2;
  };

  var _0 = function () {
    return _1() + _2();
  };

  inspect = _0;
})();
```

In other words, the mutable captured variable got initialized eagerly, which is quite reasonable in this example. And that's probably best if there are only very few captured variables that are not objects. If there are very many captured variables, or if they are huge objects, used across more than one function, then some kind of factory function might be reasonable.

**Comment by yinghuitan** [comment]
If we want to keep the delay initialization but still without duplication, one option would be generate a helper function for the delay initialization stub, like the following or similar:

```js
(function () {
  var __scope_0 = Array(1);

  var __ensure_scope_created(scope, selector) {
      var __captured__scope_1 = __scope_0[__scope_1];
      if (!__captured__scope_1) __scope_0[__scope_1] = {
        x: 13
      };
  }

  var _1 = function () {
    var __scope_1 = 0;
    __ensure_scope_created(__scope_0, __scope_1);
    var __captured__scope_1 = __scope_0[__scope_1];
    return __captured__scope_1.x += 3;
  };

  var _2 = function () {
    var __scope_1 = 0;
    __ensure_scope_created(__scope_0, __scope_1);
    var __captured__scope_1 = __scope_0[__scope_1];
    return __captured__scope_1.x -= 2;
  };

  var _0 = function () {
    return _1() + _2();
  };

  inspect = _0;
})();

```

**Comment by NTillmann** [comment]
Right. The challenge is to figure out the right heuristics when this should kick in, as by itself, adding a new function adds a ton of overhead at runtime.

**Comment by sebmarkbage** [comment]
One way to avoid that runtime overhead is by encoding it as a giant switch statement (which I think is most often encoded as a simple jump table).

```js

(function () {
  var __scope_0 = Array(1);

  var __initialize_scope_0 = function(selector) {
    var __scope = __scope_0[selector];
    if (!__scope) {
      switch (selector) {
        case 0:
          __scope = {
            x: 13
          };
      }
      __scope_0[selector] = __scope;
    }
    return __scope;
  };

  var _1 = function () {
    var __scope_1 = 0;
    var __captured__scope_1 = __initialize_scope_0(__scope_1);
    return __captured__scope_1.x += 3;
  };

  var _2 = function () {
    var __scope_1 = 0;
    var __captured__scope_1 = __initialize_scope_0(__scope_1);
    return __captured__scope_1.x -= 2;
  };

  var _0 = function () {
    return _1() + _2();
  };

  inspect = _0;
})();
```

That way you only need the one helper functions for N number of scopes.

**Comment by NTillmann** [comment]
In the long run, the big switch statement is probably the right thing we can do.
But in the short run, we are dealing with a JavaScript engine that will load into memory the entire related code (takes time and memory), and never release that memory again (still takes memory).

**Comment by sebmarkbage** [comment]
Yea the switch idea is mostly just for avoiding allocating function instances.

Wouldn't eager code loading be even more of an argument against duplicating these code branches though?

**Comment by NTillmann** [comment]
@sebmarkbage, I don't understand what you mean regarding the relationship of eager code loading and de-duplicating.
