### ISSUE TITLE
Fix type definition of Effects

### ISSUE THREAD

**Issue by JWZ2018** [facebook/prepack#962]
In the `addPriorEffects` function in `realm.js`:
`let [pc, pg, pb, pp, po] = priorEffects;`

Currently there are checks if any of `pb, pp, po` are undefined. The types of these should be changed to either allow undefined or enforce them to be defined (currently Flow is not doing so).

**Comment by hermanventer** [comment]
The type checking has improved and the specific case where undefined is expected is called out in the code. Making this completely type safe will lead to code bloat.
