### ISSUE TITLE
Support LogicalExpressions on optional abstract values

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#966]
Thanks for adding support for AbstractValue + Undefined unions. I've been trying them and I've run into a big use case where I'd expect an abstract value to be returned:

Given this example below, the object passed in is an object of `AbstractValue` + `Undefined`:
```js
function getCollectionData(collection) {
  return {
    filter: true,
    collection: collection != null && collection.items,
  };
}
```
Trying to evaluate this runs into this FatalError (which is expected as `collection` returns `true` for `arg.mightBeUndefined()`):
https://github.com/facebook/prepack/blob/da85cbdcde9f3a92846eb52f3fde8792d9854ff7/src/methods/abstract.js#L78

Ideally, this could resolve instead to an abstract value like ConditionalExpressions do? The LogicalExpression is very common in React codebases when constructing JSX expressions (as if statements aren't permitted directly), so cracking this one would be a massive win.

**Comment by hermanventer** [comment]
Working on it already. :-)

**Comment by hermanventer** [comment]
Hmm. The best I can do here is to return the join of the exception that arises if collection === undefined and the object if collection is an object. This value will be unusable unless refined in a context where "collection !== undefined" is a path condition.

**Comment by trueadm** [comment]
I can see how that affects the output. Why do we need to refine the context – because we also need to union a `NullValue`?

**Comment by hermanventer** [comment]
Looking at this some more, it seems the real problem is that "collection != null" does not refine away the undefined value in the right hand of &&. That is just a limitation of the current (extremely limited) logical for reasoning about abstract values. If you had "collection !== undefined" that would already work. I think I can beef up things to expand the path condition in the case of "!=" expressions.

**Comment by trueadm** [comment]
@hermanventer That would be great. Thank you :)

**Comment by trueadm** [comment]
@hermanventer On a side note, I came across places today where `!== null` are explicitly used, so I guess a union of `UndefinedValue` and `NullValue` would be ideal. :/

**Comment by hermanventer** [comment]
Probably not. If collection is modeled (undefined | null | object) then "!== null" only refines away the null bit and the remaining value is still unusable. I suspect you want __optional to produce (null | object) not (undefined | object).

**Comment by trueadm** [comment]
@hermanventer The issue is, the value being passed in might be `null`, `undefined` or something else – so you'd expect all those paths to be returned as possibilities. Maybe I'm not understanding something properly or I'm lacking some context. :/

**Comment by sebmarkbage** [comment]
@hermanventer Note that @trueadm's example used `collection != null` (weak comparison), not `collection !== null` (strong comparison). So it's equivalent to `collection !== null && collection !== undefined && collection.items` which would make it usable if refined twice.

**Comment by hermanventer** [comment]
@sebmarkbage Yes, if `collection != null` is used, things will work. My last comment is specific to the observation that there were places in the code where `collection !== null` is used.
