### ISSUE TITLE
Handle Possible Throw When Branching on Abstract Value

### ISSUE THREAD

**Issue by JWZ2018** [facebook/prepack#976]
```
let x = global.__abstract ? __abstract("boolean", "true") : true;
let y;
try {
  if (x) {
    y = 1;
    throw Error();
  } else {
    y = 0;
  }
}
catch(e) {
}
```
On a branch based on an abstract value where one of the branches throws and the other doesn't (example above), a fatal error occurs since the result of the evaluation is a PossiblyNormalCompletion.
Prepack should handle the join of the branches in this case.

**Comment by NTillmann** [comment]
At the very least, the resulting error code should get some help text:
https://github.com/facebook/prepack/wiki/PP0001 is not yet populated.

**Comment by hermanventer** [comment]
PP0001 is currently used for errors that are generated the old way, via reportIntrospectionError. These errors should instead be generated by calling handleError directly, with specific error codes and relevant source locations.

**Comment by JWZ2018** [comment]
I can change the error handling.
