### ISSUE TITLE
Constant propagation does not occur inside escaping functions

### ISSUE THREAD

**Issue by bakkot** [facebook/prepack#984]
```js
{
  let i = 0;
  x = i;
}
```
is correctly packed to
```js
x = 0;
```

But 
```js
foo = function ()
{
  let i = 0;
  x = i;
};
```

passes through essentially unchanged (modulo the usual wrapping), whereas I'd expect it to become more like

```js
foo = function () {
  x = 0;
};
```

I'm on 0.2.6.

**Comment by bakkot** [comment]
This is related to #632, I suppose.

**Comment by NTillmann** [comment]
This is expected, as Prepack only optimizes the global code, and not residual functions. You found the right master issue (#632), so I am closing this one as a duplicate.
