### ISSUE TITLE
Make Additional Functions work with arguments

### ISSUE THREAD

**Issue by cblappert** [facebook/prepack#987]
Currently prepacking additional functions does not properly address functions with arguments. Allow the function to have arguments which are then treated as `AbstractValue`s.

**Comment by NTillmann** [comment]
#1466 enables arguments for additional functions! @cblappert, what is your plan to further enhance this?

**Comment by cblappert** [comment]
In the future, we probably want a way to model the arguments for optimized functions (e.g. specifying that they'll always be simple objects etc).

**Comment by cblappert** [comment]
Completed by #2215
